/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package com.SIGIApp.dao;

import com.SIGIApp.dto.ItemSolicitud;
import com.SIGIApp.dto.ItemSolicitudPk;
import com.SIGIApp.exceptions.ItemSolicitudDaoException;

public interface ItemSolicitudDao
{
	/** 
	 * Inserts a new row in the ItemSolicitud table.
	 */
	public ItemSolicitudPk insert(ItemSolicitud dto) throws ItemSolicitudDaoException;

	/** 
	 * Updates a single row in the ItemSolicitud table.
	 */
	public void update(ItemSolicitudPk pk, ItemSolicitud dto) throws ItemSolicitudDaoException;

	/** 
	 * Deletes a single row in the ItemSolicitud table.
	 */
	public void delete(ItemSolicitudPk pk) throws ItemSolicitudDaoException;

	/** 
	 * Returns the rows from the ItemSolicitud table that matches the specified primary-key value.
	 */
	public ItemSolicitud findByPrimaryKey(ItemSolicitudPk pk) throws ItemSolicitudDaoException;

	/** 
	 * Returns all rows from the ItemSolicitud table that match the criteria 'idItem = :idItem'.
	 */
	public ItemSolicitud findByPrimaryKey(int idItem) throws ItemSolicitudDaoException;

	/** 
	 * Returns all rows from the ItemSolicitud table that match the criteria ''.
	 */
	public ItemSolicitud[] findAll() throws ItemSolicitudDaoException;

	/** 
	 * Returns all rows from the ItemSolicitud table that match the criteria 'idSolicitud = :idSolicitud'.
	 */
	public ItemSolicitud[] findBySolicitud(int idSolicitud) throws ItemSolicitudDaoException;

	/** 
	 * Returns all rows from the ItemSolicitud table that match the criteria 'idInsumo = :idInsumo'.
	 */
	public ItemSolicitud[] findByInsumo(int idInsumo) throws ItemSolicitudDaoException;

	/** 
	 * Returns all rows from the ItemSolicitud table that match the criteria 'idItem = :idItem'.
	 */
	public ItemSolicitud[] findWhereIdItemEquals(int idItem) throws ItemSolicitudDaoException;

	/** 
	 * Returns all rows from the ItemSolicitud table that match the criteria 'idSolicitud = :idSolicitud'.
	 */
	public ItemSolicitud[] findWhereIdSolicitudEquals(int idSolicitud) throws ItemSolicitudDaoException;

	/** 
	 * Returns all rows from the ItemSolicitud table that match the criteria 'idInsumo = :idInsumo'.
	 */
	public ItemSolicitud[] findWhereIdInsumoEquals(int idInsumo) throws ItemSolicitudDaoException;

	/** 
	 * Returns all rows from the ItemSolicitud table that match the criteria 'cantSolicitada = :cantSolicitada'.
	 */
	public ItemSolicitud[] findWhereCantSolicitadaEquals(int cantSolicitada) throws ItemSolicitudDaoException;

	/** 
	 * Returns all rows from the ItemSolicitud table that match the criteria 'cantEntregada = :cantEntregada'.
	 */
	public ItemSolicitud[] findWhereCantEntregadaEquals(int cantEntregada) throws ItemSolicitudDaoException;

	/** 
	 * Sets the value of maxRows
	 */
	public void setMaxRows(int maxRows);

	/** 
	 * Gets the value of maxRows
	 */
	public int getMaxRows();

	/** 
	 * Returns all rows from the ItemSolicitud table that match the specified arbitrary SQL statement
	 */
	public ItemSolicitud[] findByDynamicSelect(String sql, Object[] sqlParams) throws ItemSolicitudDaoException;

	/** 
	 * Returns all rows from the ItemSolicitud table that match the specified arbitrary SQL statement
	 */
	public ItemSolicitud[] findByDynamicWhere(String sql, Object[] sqlParams) throws ItemSolicitudDaoException;

}
