/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package com.SIGIApp.dao;

import com.SIGIApp.dto.UsuarioPk;
import com.SIGIApp.dto.Usuario;
import com.SIGIApp.exceptions.UsuarioDaoException;

public interface UsuarioDao
{
	/** 
	 * Inserts a new row in the Usuario table.
	 */
	public UsuarioPk insert(Usuario dto) throws UsuarioDaoException;

	/** 
	 * Updates a single row in the Usuario table.
	 */
	public void update(UsuarioPk pk, Usuario dto) throws UsuarioDaoException;

	/** 
	 * Deletes a single row in the Usuario table.
	 */
	public void delete(UsuarioPk pk) throws UsuarioDaoException;

	/** 
	 * Returns the rows from the Usuario table that matches the specified primary-key value.
	 */
	public Usuario findByPrimaryKey(UsuarioPk pk) throws UsuarioDaoException;

	/** 
	 * Returns all rows from the Usuario table that match the criteria 'idUsuario = :idUsuario'.
	 */
	public Usuario findByPrimaryKey(int idUsuario) throws UsuarioDaoException;

	/** 
	 * Returns all rows from the Usuario table that match the criteria ''.
	 */
	public Usuario[] findAll() throws UsuarioDaoException;

	/** 
	 * Returns all rows from the Usuario table that match the criteria 'idUsuario = :idUsuario'.
	 */
	public Usuario[] findWhereIdUsuarioEquals(int idUsuario) throws UsuarioDaoException;

	/** 
	 * Returns all rows from the Usuario table that match the criteria 'dni = :dni'.
	 */
	public Usuario[] findWhereDniEquals(String dni) throws UsuarioDaoException;

	/** 
	 * Returns all rows from the Usuario table that match the criteria 'nombre = :nombre'.
	 */
	public Usuario[] findWhereNombreEquals(String nombre) throws UsuarioDaoException;

	/** 
	 * Returns all rows from the Usuario table that match the criteria 'correo = :correo'.
	 */
	public Usuario[] findWhereCorreoEquals(String correo) throws UsuarioDaoException;

	/** 
	 * Returns all rows from the Usuario table that match the criteria 'contrasena = :contrasena'.
	 */
	public Usuario[] findWhereContrasenaEquals(String contrasena) throws UsuarioDaoException;

	/** 
	 * Returns all rows from the Usuario table that match the criteria 'rol = :rol'.
	 */
	public Usuario[] findWhereRolEquals(String rol) throws UsuarioDaoException;

	/** 
	 * Returns all rows from the Usuario table that match the criteria 'estado = :estado'.
	 */
	public Usuario[] findWhereEstadoEquals(short estado) throws UsuarioDaoException;

	/** 
	 * Sets the value of maxRows
	 */
	public void setMaxRows(int maxRows);

	/** 
	 * Gets the value of maxRows
	 */
	public int getMaxRows();

	/** 
	 * Returns all rows from the Usuario table that match the specified arbitrary SQL statement
	 */
	public Usuario[] findByDynamicSelect(String sql, Object[] sqlParams) throws UsuarioDaoException;

	/** 
	 * Returns all rows from the Usuario table that match the specified arbitrary SQL statement
	 */
	public Usuario[] findByDynamicWhere(String sql, Object[] sqlParams) throws UsuarioDaoException;

}
