/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package com.SIGIA.app.dto;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

/** 
 * This class represents the primary key of the Actividad table.
 */
public class ActividadPk implements Serializable
{
	protected int idActividad;

	/** 
	 * This attribute represents whether the primitive attribute idActividad is null.
	 */
	protected boolean idActividadNull;

	/** 
	 * Sets the value of idActividad
	 */
	public void setIdActividad(int idActividad)
	{
		this.idActividad = idActividad;
	}

	/** 
	 * Gets the value of idActividad
	 */
	public int getIdActividad()
	{
		return idActividad;
	}

	/**
	 * Method 'ActividadPk'
	 * 
	 */
	public ActividadPk()
	{
	}

	/**
	 * Method 'ActividadPk'
	 * 
	 * @param idActividad
	 */
	public ActividadPk(final int idActividad)
	{
		this.idActividad = idActividad;
	}

	/** 
	 * Sets the value of idActividadNull
	 */
	public void setIdActividadNull(boolean idActividadNull)
	{
		this.idActividadNull = idActividadNull;
	}

	/** 
	 * Gets the value of idActividadNull
	 */
	public boolean isIdActividadNull()
	{
		return idActividadNull;
	}

	/**
	 * Method 'equals'
	 * 
	 * @param _other
	 * @return boolean
	 */
	public boolean equals(Object _other)
	{
		if (_other == null) {
			return false;
		}
		
		if (_other == this) {
			return true;
		}
		
		if (!(_other instanceof ActividadPk)) {
			return false;
		}
		
		final ActividadPk _cast = (ActividadPk) _other;
		if (idActividad != _cast.idActividad) {
			return false;
		}
		
		if (idActividadNull != _cast.idActividadNull) {
			return false;
		}
		
		return true;
	}

	/**
	 * Method 'hashCode'
	 * 
	 * @return int
	 */
	public int hashCode()
	{
		int _hashCode = 0;
		_hashCode = 29 * _hashCode + idActividad;
		_hashCode = 29 * _hashCode + (idActividadNull ? 1 : 0);
		return _hashCode;
	}

	/**
	 * Method 'toString'
	 * 
	 * @return String
	 */
	public String toString()
	{
		StringBuffer ret = new StringBuffer();
		ret.append( "com.SIGIA.app.dto.ActividadPk: " );
		ret.append( "idActividad=" + idActividad );
		return ret.toString();
	}

}
