/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package com.SIGIA.app.dto;

import com.SIGIA.app.dao.*;
import com.SIGIA.app.factory.*;
import com.SIGIA.app.exceptions.*;
import java.io.Serializable;
import java.util.*;
import java.util.Date;

public class Actividad implements Serializable
{
	/** 
	 * This attribute maps to the column idActividad in the Actividad table.
	 */
	protected int idActividad;

	/** 
	 * This attribute maps to the column areaAfectada in the Actividad table.
	 */
	protected String areaAfectada;

	/** 
	 * This attribute maps to the column accionRealizada in the Actividad table.
	 */
	protected String accionRealizada;

	/** 
	 * This attribute maps to the column fecha in the Actividad table.
	 */
	protected Date fecha;

	/** 
	 * This attribute maps to the column descripcion in the Actividad table.
	 */
	protected String descripcion;

	/** 
	 * This attribute maps to the column idUsuario in the Actividad table.
	 */
	protected int idUsuario;

	/** 
	 * This attribute represents whether the primitive attribute idUsuario is null.
	 */
	protected boolean idUsuarioNull = true;

	/**
	 * Method 'Actividad'
	 * 
	 */
	public Actividad()
	{
	}

	/**
	 * Method 'getIdActividad'
	 * 
	 * @return int
	 */
	public int getIdActividad()
	{
		return idActividad;
	}

	/**
	 * Method 'setIdActividad'
	 * 
	 * @param idActividad
	 */
	public void setIdActividad(int idActividad)
	{
		this.idActividad = idActividad;
	}

	/**
	 * Method 'getAreaAfectada'
	 * 
	 * @return String
	 */
	public String getAreaAfectada()
	{
		return areaAfectada;
	}

	/**
	 * Method 'setAreaAfectada'
	 * 
	 * @param areaAfectada
	 */
	public void setAreaAfectada(String areaAfectada)
	{
		this.areaAfectada = areaAfectada;
	}

	/**
	 * Method 'getAccionRealizada'
	 * 
	 * @return String
	 */
	public String getAccionRealizada()
	{
		return accionRealizada;
	}

	/**
	 * Method 'setAccionRealizada'
	 * 
	 * @param accionRealizada
	 */
	public void setAccionRealizada(String accionRealizada)
	{
		this.accionRealizada = accionRealizada;
	}

	/**
	 * Method 'getFecha'
	 * 
	 * @return Date
	 */
	public Date getFecha()
	{
		return fecha;
	}

	/**
	 * Method 'setFecha'
	 * 
	 * @param fecha
	 */
	public void setFecha(Date fecha)
	{
		this.fecha = fecha;
	}

	/**
	 * Method 'getDescripcion'
	 * 
	 * @return String
	 */
	public String getDescripcion()
	{
		return descripcion;
	}

	/**
	 * Method 'setDescripcion'
	 * 
	 * @param descripcion
	 */
	public void setDescripcion(String descripcion)
	{
		this.descripcion = descripcion;
	}

	/**
	 * Method 'getIdUsuario'
	 * 
	 * @return int
	 */
	public int getIdUsuario()
	{
		return idUsuario;
	}

	/**
	 * Method 'setIdUsuario'
	 * 
	 * @param idUsuario
	 */
	public void setIdUsuario(int idUsuario)
	{
		this.idUsuario = idUsuario;
		this.idUsuarioNull = false;
	}

	/**
	 * Method 'setIdUsuarioNull'
	 * 
	 * @param value
	 */
	public void setIdUsuarioNull(boolean value)
	{
		this.idUsuarioNull = value;
	}

	/**
	 * Method 'isIdUsuarioNull'
	 * 
	 * @return boolean
	 */
	public boolean isIdUsuarioNull()
	{
		return idUsuarioNull;
	}

	/**
	 * Method 'equals'
	 * 
	 * @param _other
	 * @return boolean
	 */
	public boolean equals(Object _other)
	{
		if (_other == null) {
			return false;
		}
		
		if (_other == this) {
			return true;
		}
		
		if (!(_other instanceof Actividad)) {
			return false;
		}
		
		final Actividad _cast = (Actividad) _other;
		if (idActividad != _cast.idActividad) {
			return false;
		}
		
		if (areaAfectada == null ? _cast.areaAfectada != areaAfectada : !areaAfectada.equals( _cast.areaAfectada )) {
			return false;
		}
		
		if (accionRealizada == null ? _cast.accionRealizada != accionRealizada : !accionRealizada.equals( _cast.accionRealizada )) {
			return false;
		}
		
		if (fecha == null ? _cast.fecha != fecha : !fecha.equals( _cast.fecha )) {
			return false;
		}
		
		if (descripcion == null ? _cast.descripcion != descripcion : !descripcion.equals( _cast.descripcion )) {
			return false;
		}
		
		if (idUsuario != _cast.idUsuario) {
			return false;
		}
		
		if (idUsuarioNull != _cast.idUsuarioNull) {
			return false;
		}
		
		return true;
	}

	/**
	 * Method 'hashCode'
	 * 
	 * @return int
	 */
	public int hashCode()
	{
		int _hashCode = 0;
		_hashCode = 29 * _hashCode + idActividad;
		if (areaAfectada != null) {
			_hashCode = 29 * _hashCode + areaAfectada.hashCode();
		}
		
		if (accionRealizada != null) {
			_hashCode = 29 * _hashCode + accionRealizada.hashCode();
		}
		
		if (fecha != null) {
			_hashCode = 29 * _hashCode + fecha.hashCode();
		}
		
		if (descripcion != null) {
			_hashCode = 29 * _hashCode + descripcion.hashCode();
		}
		
		_hashCode = 29 * _hashCode + idUsuario;
		_hashCode = 29 * _hashCode + (idUsuarioNull ? 1 : 0);
		return _hashCode;
	}

	/**
	 * Method 'createPk'
	 * 
	 * @return ActividadPk
	 */
	public ActividadPk createPk()
	{
		return new ActividadPk(idActividad);
	}

	/**
	 * Method 'toString'
	 * 
	 * @return String
	 */
	public String toString()
	{
		StringBuffer ret = new StringBuffer();
		ret.append( "com.SIGIA.app.dto.Actividad: " );
		ret.append( "idActividad=" + idActividad );
		ret.append( ", areaAfectada=" + areaAfectada );
		ret.append( ", accionRealizada=" + accionRealizada );
		ret.append( ", fecha=" + fecha );
		ret.append( ", descripcion=" + descripcion );
		ret.append( ", idUsuario=" + idUsuario );
		return ret.toString();
	}

}
