/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package com.SIGIA.app.dto;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

/** 
 * This class represents the primary key of the Insumo table.
 */
public class InsumoPk implements Serializable
{
	protected int idInsumo;

	/** 
	 * This attribute represents whether the primitive attribute idInsumo is null.
	 */
	protected boolean idInsumoNull;

	/** 
	 * Sets the value of idInsumo
	 */
	public void setIdInsumo(int idInsumo)
	{
		this.idInsumo = idInsumo;
	}

	/** 
	 * Gets the value of idInsumo
	 */
	public int getIdInsumo()
	{
		return idInsumo;
	}

	/**
	 * Method 'InsumoPk'
	 * 
	 */
	public InsumoPk()
	{
	}

	/**
	 * Method 'InsumoPk'
	 * 
	 * @param idInsumo
	 */
	public InsumoPk(final int idInsumo)
	{
		this.idInsumo = idInsumo;
	}

	/** 
	 * Sets the value of idInsumoNull
	 */
	public void setIdInsumoNull(boolean idInsumoNull)
	{
		this.idInsumoNull = idInsumoNull;
	}

	/** 
	 * Gets the value of idInsumoNull
	 */
	public boolean isIdInsumoNull()
	{
		return idInsumoNull;
	}

	/**
	 * Method 'equals'
	 * 
	 * @param _other
	 * @return boolean
	 */
	public boolean equals(Object _other)
	{
		if (_other == null) {
			return false;
		}
		
		if (_other == this) {
			return true;
		}
		
		if (!(_other instanceof InsumoPk)) {
			return false;
		}
		
		final InsumoPk _cast = (InsumoPk) _other;
		if (idInsumo != _cast.idInsumo) {
			return false;
		}
		
		if (idInsumoNull != _cast.idInsumoNull) {
			return false;
		}
		
		return true;
	}

	/**
	 * Method 'hashCode'
	 * 
	 * @return int
	 */
	public int hashCode()
	{
		int _hashCode = 0;
		_hashCode = 29 * _hashCode + idInsumo;
		_hashCode = 29 * _hashCode + (idInsumoNull ? 1 : 0);
		return _hashCode;
	}

	/**
	 * Method 'toString'
	 * 
	 * @return String
	 */
	public String toString()
	{
		StringBuffer ret = new StringBuffer();
		ret.append( "com.SIGIA.app.dto.InsumoPk: " );
		ret.append( "idInsumo=" + idInsumo );
		return ret.toString();
	}

}
