/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package com.SIGIA.app.dto;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

/** 
 * This class represents the primary key of the ItemSolicitud table.
 */
public class ItemSolicitudPk implements Serializable
{
	protected int idItem;

	/** 
	 * This attribute represents whether the primitive attribute idItem is null.
	 */
	protected boolean idItemNull;

	/** 
	 * Sets the value of idItem
	 */
	public void setIdItem(int idItem)
	{
		this.idItem = idItem;
	}

	/** 
	 * Gets the value of idItem
	 */
	public int getIdItem()
	{
		return idItem;
	}

	/**
	 * Method 'ItemSolicitudPk'
	 * 
	 */
	public ItemSolicitudPk()
	{
	}

	/**
	 * Method 'ItemSolicitudPk'
	 * 
	 * @param idItem
	 */
	public ItemSolicitudPk(final int idItem)
	{
		this.idItem = idItem;
	}

	/** 
	 * Sets the value of idItemNull
	 */
	public void setIdItemNull(boolean idItemNull)
	{
		this.idItemNull = idItemNull;
	}

	/** 
	 * Gets the value of idItemNull
	 */
	public boolean isIdItemNull()
	{
		return idItemNull;
	}

	/**
	 * Method 'equals'
	 * 
	 * @param _other
	 * @return boolean
	 */
	public boolean equals(Object _other)
	{
		if (_other == null) {
			return false;
		}
		
		if (_other == this) {
			return true;
		}
		
		if (!(_other instanceof ItemSolicitudPk)) {
			return false;
		}
		
		final ItemSolicitudPk _cast = (ItemSolicitudPk) _other;
		if (idItem != _cast.idItem) {
			return false;
		}
		
		if (idItemNull != _cast.idItemNull) {
			return false;
		}
		
		return true;
	}

	/**
	 * Method 'hashCode'
	 * 
	 * @return int
	 */
	public int hashCode()
	{
		int _hashCode = 0;
		_hashCode = 29 * _hashCode + idItem;
		_hashCode = 29 * _hashCode + (idItemNull ? 1 : 0);
		return _hashCode;
	}

	/**
	 * Method 'toString'
	 * 
	 * @return String
	 */
	public String toString()
	{
		StringBuffer ret = new StringBuffer();
		ret.append( "com.SIGIA.app.dto.ItemSolicitudPk: " );
		ret.append( "idItem=" + idItem );
		return ret.toString();
	}

}
