/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package com.SIGIA.app.dto;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

/** 
 * This class represents the primary key of the Solicitud table.
 */
public class SolicitudPk implements Serializable
{
	protected int idSolicitud;

	/** 
	 * This attribute represents whether the primitive attribute idSolicitud is null.
	 */
	protected boolean idSolicitudNull;

	/** 
	 * Sets the value of idSolicitud
	 */
	public void setIdSolicitud(int idSolicitud)
	{
		this.idSolicitud = idSolicitud;
	}

	/** 
	 * Gets the value of idSolicitud
	 */
	public int getIdSolicitud()
	{
		return idSolicitud;
	}

	/**
	 * Method 'SolicitudPk'
	 * 
	 */
	public SolicitudPk()
	{
	}

	/**
	 * Method 'SolicitudPk'
	 * 
	 * @param idSolicitud
	 */
	public SolicitudPk(final int idSolicitud)
	{
		this.idSolicitud = idSolicitud;
	}

	/** 
	 * Sets the value of idSolicitudNull
	 */
	public void setIdSolicitudNull(boolean idSolicitudNull)
	{
		this.idSolicitudNull = idSolicitudNull;
	}

	/** 
	 * Gets the value of idSolicitudNull
	 */
	public boolean isIdSolicitudNull()
	{
		return idSolicitudNull;
	}

	/**
	 * Method 'equals'
	 * 
	 * @param _other
	 * @return boolean
	 */
	public boolean equals(Object _other)
	{
		if (_other == null) {
			return false;
		}
		
		if (_other == this) {
			return true;
		}
		
		if (!(_other instanceof SolicitudPk)) {
			return false;
		}
		
		final SolicitudPk _cast = (SolicitudPk) _other;
		if (idSolicitud != _cast.idSolicitud) {
			return false;
		}
		
		if (idSolicitudNull != _cast.idSolicitudNull) {
			return false;
		}
		
		return true;
	}

	/**
	 * Method 'hashCode'
	 * 
	 * @return int
	 */
	public int hashCode()
	{
		int _hashCode = 0;
		_hashCode = 29 * _hashCode + idSolicitud;
		_hashCode = 29 * _hashCode + (idSolicitudNull ? 1 : 0);
		return _hashCode;
	}

	/**
	 * Method 'toString'
	 * 
	 * @return String
	 */
	public String toString()
	{
		StringBuffer ret = new StringBuffer();
		ret.append( "com.SIGIA.app.dto.SolicitudPk: " );
		ret.append( "idSolicitud=" + idSolicitud );
		return ret.toString();
	}

}
