/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package com.SIGIA.app.dto;

import com.SIGIA.app.dao.*;
import com.SIGIA.app.factory.*;
import com.SIGIA.app.exceptions.*;
import java.io.Serializable;
import java.util.*;
import java.util.Date;

public class Solicitud implements Serializable
{
	/** 
	 * This attribute maps to the column idSolicitud in the Solicitud table.
	 */
	protected int idSolicitud;

	/** 
	 * This attribute maps to the column nroTramite in the Solicitud table.
	 */
	protected String nroTramite;

	/** 
	 * This attribute maps to the column fecha in the Solicitud table.
	 */
	protected Date fecha;

	/** 
	 * This attribute maps to the column estado in the Solicitud table.
	 */
	protected String estado;

	/** 
	 * This attribute maps to the column area in the Solicitud table.
	 */
	protected String area;

	/** 
	 * This attribute maps to the column solicitante in the Solicitud table.
	 */
	protected String solicitante;

	/**
	 * Method 'Solicitud'
	 * 
	 */
	public Solicitud()
	{
	}

	/**
	 * Method 'getIdSolicitud'
	 * 
	 * @return int
	 */
	public int getIdSolicitud()
	{
		return idSolicitud;
	}

	/**
	 * Method 'setIdSolicitud'
	 * 
	 * @param idSolicitud
	 */
	public void setIdSolicitud(int idSolicitud)
	{
		this.idSolicitud = idSolicitud;
	}

	/**
	 * Method 'getNroTramite'
	 * 
	 * @return String
	 */
	public String getNroTramite()
	{
		return nroTramite;
	}

	/**
	 * Method 'setNroTramite'
	 * 
	 * @param nroTramite
	 */
	public void setNroTramite(String nroTramite)
	{
		this.nroTramite = nroTramite;
	}

	/**
	 * Method 'getFecha'
	 * 
	 * @return Date
	 */
	public Date getFecha()
	{
		return fecha;
	}

	/**
	 * Method 'setFecha'
	 * 
	 * @param fecha
	 */
	public void setFecha(Date fecha)
	{
		this.fecha = fecha;
	}

	/**
	 * Method 'getEstado'
	 * 
	 * @return String
	 */
	public String getEstado()
	{
		return estado;
	}

	/**
	 * Method 'setEstado'
	 * 
	 * @param estado
	 */
	public void setEstado(String estado)
	{
		this.estado = estado;
	}

	/**
	 * Method 'getArea'
	 * 
	 * @return String
	 */
	public String getArea()
	{
		return area;
	}

	/**
	 * Method 'setArea'
	 * 
	 * @param area
	 */
	public void setArea(String area)
	{
		this.area = area;
	}

	/**
	 * Method 'getSolicitante'
	 * 
	 * @return String
	 */
	public String getSolicitante()
	{
		return solicitante;
	}

	/**
	 * Method 'setSolicitante'
	 * 
	 * @param solicitante
	 */
	public void setSolicitante(String solicitante)
	{
		this.solicitante = solicitante;
	}

	/**
	 * Method 'equals'
	 * 
	 * @param _other
	 * @return boolean
	 */
	public boolean equals(Object _other)
	{
		if (_other == null) {
			return false;
		}
		
		if (_other == this) {
			return true;
		}
		
		if (!(_other instanceof Solicitud)) {
			return false;
		}
		
		final Solicitud _cast = (Solicitud) _other;
		if (idSolicitud != _cast.idSolicitud) {
			return false;
		}
		
		if (nroTramite == null ? _cast.nroTramite != nroTramite : !nroTramite.equals( _cast.nroTramite )) {
			return false;
		}
		
		if (fecha == null ? _cast.fecha != fecha : !fecha.equals( _cast.fecha )) {
			return false;
		}
		
		if (estado == null ? _cast.estado != estado : !estado.equals( _cast.estado )) {
			return false;
		}
		
		if (area == null ? _cast.area != area : !area.equals( _cast.area )) {
			return false;
		}
		
		if (solicitante == null ? _cast.solicitante != solicitante : !solicitante.equals( _cast.solicitante )) {
			return false;
		}
		
		return true;
	}

	/**
	 * Method 'hashCode'
	 * 
	 * @return int
	 */
	public int hashCode()
	{
		int _hashCode = 0;
		_hashCode = 29 * _hashCode + idSolicitud;
		if (nroTramite != null) {
			_hashCode = 29 * _hashCode + nroTramite.hashCode();
		}
		
		if (fecha != null) {
			_hashCode = 29 * _hashCode + fecha.hashCode();
		}
		
		if (estado != null) {
			_hashCode = 29 * _hashCode + estado.hashCode();
		}
		
		if (area != null) {
			_hashCode = 29 * _hashCode + area.hashCode();
		}
		
		if (solicitante != null) {
			_hashCode = 29 * _hashCode + solicitante.hashCode();
		}
		
		return _hashCode;
	}

	/**
	 * Method 'createPk'
	 * 
	 * @return SolicitudPk
	 */
	public SolicitudPk createPk()
	{
		return new SolicitudPk(idSolicitud);
	}

	/**
	 * Method 'toString'
	 * 
	 * @return String
	 */
	public String toString()
	{
		StringBuffer ret = new StringBuffer();
		ret.append( "com.SIGIA.app.dto.Solicitud: " );
		ret.append( "idSolicitud=" + idSolicitud );
		ret.append( ", nroTramite=" + nroTramite );
		ret.append( ", fecha=" + fecha );
		ret.append( ", estado=" + estado );
		ret.append( ", area=" + area );
		ret.append( ", solicitante=" + solicitante );
		return ret.toString();
	}

}
