/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package com.SIGIA.app.dto;

import com.SIGIA.app.dao.*;
import com.SIGIA.app.factory.*;
import com.SIGIA.app.exceptions.*;
import java.io.Serializable;
import java.util.*;
import java.util.Date;

public class Transaccion implements Serializable
{
	/** 
	 * This attribute maps to the column idTransaccion in the Transaccion table.
	 */
	protected int idTransaccion;

	/** 
	 * This attribute maps to the column tipo in the Transaccion table.
	 */
	protected String tipo;

	/** 
	 * This attribute maps to the column fecha in the Transaccion table.
	 */
	protected Date fecha;

	/** 
	 * This attribute maps to the column cantidad in the Transaccion table.
	 */
	protected int cantidad;

	/** 
	 * This attribute represents whether the primitive attribute cantidad is null.
	 */
	protected boolean cantidadNull = true;

	/** 
	 * This attribute maps to the column areaDestino in the Transaccion table.
	 */
	protected String areaDestino;

	/** 
	 * This attribute maps to the column solicitante in the Transaccion table.
	 */
	protected String solicitante;

	/** 
	 * This attribute maps to the column idInsumo in the Transaccion table.
	 */
	protected int idInsumo;

	/** 
	 * This attribute represents whether the primitive attribute idInsumo is null.
	 */
	protected boolean idInsumoNull = true;

	/** 
	 * This attribute maps to the column idUsuario in the Transaccion table.
	 */
	protected int idUsuario;

	/** 
	 * This attribute represents whether the primitive attribute idUsuario is null.
	 */
	protected boolean idUsuarioNull = true;

	/**
	 * Method 'Transaccion'
	 * 
	 */
	public Transaccion()
	{
	}

	/**
	 * Method 'getIdTransaccion'
	 * 
	 * @return int
	 */
	public int getIdTransaccion()
	{
		return idTransaccion;
	}

	/**
	 * Method 'setIdTransaccion'
	 * 
	 * @param idTransaccion
	 */
	public void setIdTransaccion(int idTransaccion)
	{
		this.idTransaccion = idTransaccion;
	}

	/**
	 * Method 'getTipo'
	 * 
	 * @return String
	 */
	public String getTipo()
	{
		return tipo;
	}

	/**
	 * Method 'setTipo'
	 * 
	 * @param tipo
	 */
	public void setTipo(String tipo)
	{
		this.tipo = tipo;
	}

	/**
	 * Method 'getFecha'
	 * 
	 * @return Date
	 */
	public Date getFecha()
	{
		return fecha;
	}

	/**
	 * Method 'setFecha'
	 * 
	 * @param fecha
	 */
	public void setFecha(Date fecha)
	{
		this.fecha = fecha;
	}

	/**
	 * Method 'getCantidad'
	 * 
	 * @return int
	 */
	public int getCantidad()
	{
		return cantidad;
	}

	/**
	 * Method 'setCantidad'
	 * 
	 * @param cantidad
	 */
	public void setCantidad(int cantidad)
	{
		this.cantidad = cantidad;
		this.cantidadNull = false;
	}

	/**
	 * Method 'setCantidadNull'
	 * 
	 * @param value
	 */
	public void setCantidadNull(boolean value)
	{
		this.cantidadNull = value;
	}

	/**
	 * Method 'isCantidadNull'
	 * 
	 * @return boolean
	 */
	public boolean isCantidadNull()
	{
		return cantidadNull;
	}

	/**
	 * Method 'getAreaDestino'
	 * 
	 * @return String
	 */
	public String getAreaDestino()
	{
		return areaDestino;
	}

	/**
	 * Method 'setAreaDestino'
	 * 
	 * @param areaDestino
	 */
	public void setAreaDestino(String areaDestino)
	{
		this.areaDestino = areaDestino;
	}

	/**
	 * Method 'getSolicitante'
	 * 
	 * @return String
	 */
	public String getSolicitante()
	{
		return solicitante;
	}

	/**
	 * Method 'setSolicitante'
	 * 
	 * @param solicitante
	 */
	public void setSolicitante(String solicitante)
	{
		this.solicitante = solicitante;
	}

	/**
	 * Method 'getIdInsumo'
	 * 
	 * @return int
	 */
	public int getIdInsumo()
	{
		return idInsumo;
	}

	/**
	 * Method 'setIdInsumo'
	 * 
	 * @param idInsumo
	 */
	public void setIdInsumo(int idInsumo)
	{
		this.idInsumo = idInsumo;
		this.idInsumoNull = false;
	}

	/**
	 * Method 'setIdInsumoNull'
	 * 
	 * @param value
	 */
	public void setIdInsumoNull(boolean value)
	{
		this.idInsumoNull = value;
	}

	/**
	 * Method 'isIdInsumoNull'
	 * 
	 * @return boolean
	 */
	public boolean isIdInsumoNull()
	{
		return idInsumoNull;
	}

	/**
	 * Method 'getIdUsuario'
	 * 
	 * @return int
	 */
	public int getIdUsuario()
	{
		return idUsuario;
	}

	/**
	 * Method 'setIdUsuario'
	 * 
	 * @param idUsuario
	 */
	public void setIdUsuario(int idUsuario)
	{
		this.idUsuario = idUsuario;
		this.idUsuarioNull = false;
	}

	/**
	 * Method 'setIdUsuarioNull'
	 * 
	 * @param value
	 */
	public void setIdUsuarioNull(boolean value)
	{
		this.idUsuarioNull = value;
	}

	/**
	 * Method 'isIdUsuarioNull'
	 * 
	 * @return boolean
	 */
	public boolean isIdUsuarioNull()
	{
		return idUsuarioNull;
	}

	/**
	 * Method 'equals'
	 * 
	 * @param _other
	 * @return boolean
	 */
	public boolean equals(Object _other)
	{
		if (_other == null) {
			return false;
		}
		
		if (_other == this) {
			return true;
		}
		
		if (!(_other instanceof Transaccion)) {
			return false;
		}
		
		final Transaccion _cast = (Transaccion) _other;
		if (idTransaccion != _cast.idTransaccion) {
			return false;
		}
		
		if (tipo == null ? _cast.tipo != tipo : !tipo.equals( _cast.tipo )) {
			return false;
		}
		
		if (fecha == null ? _cast.fecha != fecha : !fecha.equals( _cast.fecha )) {
			return false;
		}
		
		if (cantidad != _cast.cantidad) {
			return false;
		}
		
		if (cantidadNull != _cast.cantidadNull) {
			return false;
		}
		
		if (areaDestino == null ? _cast.areaDestino != areaDestino : !areaDestino.equals( _cast.areaDestino )) {
			return false;
		}
		
		if (solicitante == null ? _cast.solicitante != solicitante : !solicitante.equals( _cast.solicitante )) {
			return false;
		}
		
		if (idInsumo != _cast.idInsumo) {
			return false;
		}
		
		if (idInsumoNull != _cast.idInsumoNull) {
			return false;
		}
		
		if (idUsuario != _cast.idUsuario) {
			return false;
		}
		
		if (idUsuarioNull != _cast.idUsuarioNull) {
			return false;
		}
		
		return true;
	}

	/**
	 * Method 'hashCode'
	 * 
	 * @return int
	 */
	public int hashCode()
	{
		int _hashCode = 0;
		_hashCode = 29 * _hashCode + idTransaccion;
		if (tipo != null) {
			_hashCode = 29 * _hashCode + tipo.hashCode();
		}
		
		if (fecha != null) {
			_hashCode = 29 * _hashCode + fecha.hashCode();
		}
		
		_hashCode = 29 * _hashCode + cantidad;
		_hashCode = 29 * _hashCode + (cantidadNull ? 1 : 0);
		if (areaDestino != null) {
			_hashCode = 29 * _hashCode + areaDestino.hashCode();
		}
		
		if (solicitante != null) {
			_hashCode = 29 * _hashCode + solicitante.hashCode();
		}
		
		_hashCode = 29 * _hashCode + idInsumo;
		_hashCode = 29 * _hashCode + (idInsumoNull ? 1 : 0);
		_hashCode = 29 * _hashCode + idUsuario;
		_hashCode = 29 * _hashCode + (idUsuarioNull ? 1 : 0);
		return _hashCode;
	}

	/**
	 * Method 'createPk'
	 * 
	 * @return TransaccionPk
	 */
	public TransaccionPk createPk()
	{
		return new TransaccionPk(idTransaccion);
	}

	/**
	 * Method 'toString'
	 * 
	 * @return String
	 */
	public String toString()
	{
		StringBuffer ret = new StringBuffer();
		ret.append( "com.SIGIA.app.dto.Transaccion: " );
		ret.append( "idTransaccion=" + idTransaccion );
		ret.append( ", tipo=" + tipo );
		ret.append( ", fecha=" + fecha );
		ret.append( ", cantidad=" + cantidad );
		ret.append( ", areaDestino=" + areaDestino );
		ret.append( ", solicitante=" + solicitante );
		ret.append( ", idInsumo=" + idInsumo );
		ret.append( ", idUsuario=" + idUsuario );
		return ret.toString();
	}

}
