/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package com.SIGIApp.jdbc;

import com.SIGIApp.dto.Solicitud;
import com.SIGIApp.dto.SolicitudPk;
import com.SIGIApp.exceptions.SolicitudDaoException;
import com.SIGIApp.dao.SolicitudDao;
import java.util.Date;
import java.sql.Connection;
import java.util.Collection;
import java.sql.PreparedStatement;
import java.sql.Statement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Time;
import java.util.List;
import java.util.Iterator;
import java.util.ArrayList;

public class SolicitudDaoImpl extends AbstractDAO implements SolicitudDao
{
	/** 
	 * The factory class for this DAO has two versions of the create() method - one that
takes no arguments and one that takes a Connection argument. If the Connection version
is chosen then the connection will be stored in this attribute and will be used by all
calls to this DAO, otherwise a new Connection will be allocated for each operation.
	 */
	protected java.sql.Connection userConn;

	/** 
	 * All finder methods in this class use this SELECT constant to build their queries
	 */
	protected final String SQL_SELECT = "SELECT idSolicitud, nroTramite, fecha, estado, area, solicitante FROM " + getTableName() + "";

	/** 
	 * Finder methods will pass this value to the JDBC setMaxRows method
	 */
	protected int maxRows;

	/** 
	 * SQL INSERT statement for this table
	 */
	protected final String SQL_INSERT = "INSERT INTO " + getTableName() + " ( idSolicitud, nroTramite, fecha, estado, area, solicitante ) VALUES ( ?, ?, ?, ?, ?, ? )";

	/** 
	 * SQL UPDATE statement for this table
	 */
	protected final String SQL_UPDATE = "UPDATE " + getTableName() + " SET idSolicitud = ?, nroTramite = ?, fecha = ?, estado = ?, area = ?, solicitante = ? WHERE idSolicitud = ?";

	/** 
	 * SQL DELETE statement for this table
	 */
	protected final String SQL_DELETE = "DELETE FROM " + getTableName() + " WHERE idSolicitud = ?";

	/** 
	 * Index of column idSolicitud
	 */
	protected static final int COLUMN_ID_SOLICITUD = 1;

	/** 
	 * Index of column nroTramite
	 */
	protected static final int COLUMN_NRO_TRAMITE = 2;

	/** 
	 * Index of column fecha
	 */
	protected static final int COLUMN_FECHA = 3;

	/** 
	 * Index of column estado
	 */
	protected static final int COLUMN_ESTADO = 4;

	/** 
	 * Index of column area
	 */
	protected static final int COLUMN_AREA = 5;

	/** 
	 * Index of column solicitante
	 */
	protected static final int COLUMN_SOLICITANTE = 6;

	/** 
	 * Number of columns
	 */
	protected static final int NUMBER_OF_COLUMNS = 6;

	/** 
	 * Index of primary-key column idSolicitud
	 */
	protected static final int PK_COLUMN_ID_SOLICITUD = 1;

	/** 
	 * Inserts a new row in the Solicitud table.
	 */
	public SolicitudPk insert(Solicitud dto) throws SolicitudDaoException
	{
		long t1 = System.currentTimeMillis();
		// declare variables
		final boolean isConnSupplied = (userConn != null);
		Connection conn = null;
		PreparedStatement stmt = null;
		ResultSet rs = null;
		
		try {
			// get the user-specified connection or get a connection from the ResourceManager
			conn = isConnSupplied ? userConn : ResourceManager.getConnection();
		
			stmt = conn.prepareStatement( SQL_INSERT, Statement.RETURN_GENERATED_KEYS );
			int index = 1;
			stmt.setInt( index++, dto.getIdSolicitud() );
			stmt.setString( index++, dto.getNroTramite() );
			stmt.setDate(index++, dto.getFecha()==null ? null : new java.sql.Date( dto.getFecha().getTime() ) );
			stmt.setString( index++, dto.getEstado() );
			stmt.setString( index++, dto.getArea() );
			stmt.setString( index++, dto.getSolicitante() );
			System.out.println( "Executing " + SQL_INSERT + " with DTO: " + dto );
			int rows = stmt.executeUpdate();
			long t2 = System.currentTimeMillis();
			System.out.println( rows + " rows affected (" + (t2-t1) + " ms)" );
		
			// retrieve values from auto-increment columns
			rs = stmt.getGeneratedKeys();
			if (rs != null && rs.next()) {
				dto.setIdSolicitud( rs.getInt( 1 ) );
			}
		
			reset(dto);
			return dto.createPk();
		}
		catch (Exception _e) {
			_e.printStackTrace();
			throw new SolicitudDaoException( "Exception: " + _e.getMessage(), _e );
		}
		finally {
			ResourceManager.close(stmt);
			if (!isConnSupplied) {
				ResourceManager.close(conn);
			}
		
		}
		
	}

	/** 
	 * Updates a single row in the Solicitud table.
	 */
	public void update(SolicitudPk pk, Solicitud dto) throws SolicitudDaoException
	{
		long t1 = System.currentTimeMillis();
		// declare variables
		final boolean isConnSupplied = (userConn != null);
		Connection conn = null;
		PreparedStatement stmt = null;
		
		try {
			// get the user-specified connection or get a connection from the ResourceManager
			conn = isConnSupplied ? userConn : ResourceManager.getConnection();
		
			System.out.println( "Executing " + SQL_UPDATE + " with DTO: " + dto );
			stmt = conn.prepareStatement( SQL_UPDATE );
			int index=1;
			stmt.setInt( index++, dto.getIdSolicitud() );
			stmt.setString( index++, dto.getNroTramite() );
			stmt.setDate(index++, dto.getFecha()==null ? null : new java.sql.Date( dto.getFecha().getTime() ) );
			stmt.setString( index++, dto.getEstado() );
			stmt.setString( index++, dto.getArea() );
			stmt.setString( index++, dto.getSolicitante() );
			stmt.setInt( 7, pk.getIdSolicitud() );
			int rows = stmt.executeUpdate();
			reset(dto);
			long t2 = System.currentTimeMillis();
			System.out.println( rows + " rows affected (" + (t2-t1) + " ms)" );
		}
		catch (Exception _e) {
			_e.printStackTrace();
			throw new SolicitudDaoException( "Exception: " + _e.getMessage(), _e );
		}
		finally {
			ResourceManager.close(stmt);
			if (!isConnSupplied) {
				ResourceManager.close(conn);
			}
		
		}
		
	}

	/** 
	 * Deletes a single row in the Solicitud table.
	 */
	public void delete(SolicitudPk pk) throws SolicitudDaoException
	{
		long t1 = System.currentTimeMillis();
		// declare variables
		final boolean isConnSupplied = (userConn != null);
		Connection conn = null;
		PreparedStatement stmt = null;
		
		try {
			// get the user-specified connection or get a connection from the ResourceManager
			conn = isConnSupplied ? userConn : ResourceManager.getConnection();
		
			System.out.println( "Executing " + SQL_DELETE + " with PK: " + pk );
			stmt = conn.prepareStatement( SQL_DELETE );
			stmt.setInt( 1, pk.getIdSolicitud() );
			int rows = stmt.executeUpdate();
			long t2 = System.currentTimeMillis();
			System.out.println( rows + " rows affected (" + (t2-t1) + " ms)" );
		}
		catch (Exception _e) {
			_e.printStackTrace();
			throw new SolicitudDaoException( "Exception: " + _e.getMessage(), _e );
		}
		finally {
			ResourceManager.close(stmt);
			if (!isConnSupplied) {
				ResourceManager.close(conn);
			}
		
		}
		
	}

	/** 
	 * Returns the rows from the Solicitud table that matches the specified primary-key value.
	 */
	public Solicitud findByPrimaryKey(SolicitudPk pk) throws SolicitudDaoException
	{
		return findByPrimaryKey( pk.getIdSolicitud() );
	}

	/** 
	 * Returns all rows from the Solicitud table that match the criteria 'idSolicitud = :idSolicitud'.
	 */
	public Solicitud findByPrimaryKey(int idSolicitud) throws SolicitudDaoException
	{
		Solicitud ret[] = findByDynamicSelect( SQL_SELECT + " WHERE idSolicitud = ?", new Object[] {  new Integer(idSolicitud) } );
		return ret.length==0 ? null : ret[0];
	}

	/** 
	 * Returns all rows from the Solicitud table that match the criteria ''.
	 */
	public Solicitud[] findAll() throws SolicitudDaoException
	{
		return findByDynamicSelect( SQL_SELECT + " ORDER BY idSolicitud", null );
	}

	/** 
	 * Returns all rows from the Solicitud table that match the criteria 'idSolicitud = :idSolicitud'.
	 */
	public Solicitud[] findWhereIdSolicitudEquals(int idSolicitud) throws SolicitudDaoException
	{
		return findByDynamicSelect( SQL_SELECT + " WHERE idSolicitud = ? ORDER BY idSolicitud", new Object[] {  new Integer(idSolicitud) } );
	}

	/** 
	 * Returns all rows from the Solicitud table that match the criteria 'nroTramite = :nroTramite'.
	 */
	public Solicitud[] findWhereNroTramiteEquals(String nroTramite) throws SolicitudDaoException
	{
		return findByDynamicSelect( SQL_SELECT + " WHERE nroTramite = ? ORDER BY nroTramite", new Object[] { nroTramite } );
	}

	/** 
	 * Returns all rows from the Solicitud table that match the criteria 'fecha = :fecha'.
	 */
	public Solicitud[] findWhereFechaEquals(Date fecha) throws SolicitudDaoException
	{
		return findByDynamicSelect( SQL_SELECT + " WHERE fecha = ? ORDER BY fecha", new Object[] { fecha==null ? null : new java.sql.Date( fecha.getTime() ) } );
	}

	/** 
	 * Returns all rows from the Solicitud table that match the criteria 'estado = :estado'.
	 */
	public Solicitud[] findWhereEstadoEquals(String estado) throws SolicitudDaoException
	{
		return findByDynamicSelect( SQL_SELECT + " WHERE estado = ? ORDER BY estado", new Object[] { estado } );
	}

	/** 
	 * Returns all rows from the Solicitud table that match the criteria 'area = :area'.
	 */
	public Solicitud[] findWhereAreaEquals(String area) throws SolicitudDaoException
	{
		return findByDynamicSelect( SQL_SELECT + " WHERE area = ? ORDER BY area", new Object[] { area } );
	}

	/** 
	 * Returns all rows from the Solicitud table that match the criteria 'solicitante = :solicitante'.
	 */
	public Solicitud[] findWhereSolicitanteEquals(String solicitante) throws SolicitudDaoException
	{
		return findByDynamicSelect( SQL_SELECT + " WHERE solicitante = ? ORDER BY solicitante", new Object[] { solicitante } );
	}

	/**
	 * Method 'SolicitudDaoImpl'
	 * 
	 */
	public SolicitudDaoImpl()
	{
	}

	/**
	 * Method 'SolicitudDaoImpl'
	 * 
	 * @param userConn
	 */
	public SolicitudDaoImpl(final java.sql.Connection userConn)
	{
		this.userConn = userConn;
	}

	/** 
	 * Sets the value of maxRows
	 */
	public void setMaxRows(int maxRows)
	{
		this.maxRows = maxRows;
	}

	/** 
	 * Gets the value of maxRows
	 */
	public int getMaxRows()
	{
		return maxRows;
	}

	/**
	 * Method 'getTableName'
	 * 
	 * @return String
	 */
	public String getTableName()
	{
		return "Solicitud";
	}

	/** 
	 * Fetches a single row from the result set
	 */
	protected Solicitud fetchSingleResult(ResultSet rs) throws SQLException
	{
		if (rs.next()) {
			Solicitud dto = new Solicitud();
			populateDto( dto, rs);
			return dto;
		} else {
			return null;
		}
		
	}

	/** 
	 * Fetches multiple rows from the result set
	 */
	protected Solicitud[] fetchMultiResults(ResultSet rs) throws SQLException
	{
		Collection resultList = new ArrayList();
		while (rs.next()) {
			Solicitud dto = new Solicitud();
			populateDto( dto, rs);
			resultList.add( dto );
		}
		
		Solicitud ret[] = new Solicitud[ resultList.size() ];
		resultList.toArray( ret );
		return ret;
	}

	/** 
	 * Populates a DTO with data from a ResultSet
	 */
	protected void populateDto(Solicitud dto, ResultSet rs) throws SQLException
	{
		dto.setIdSolicitud( rs.getInt( COLUMN_ID_SOLICITUD ) );
		dto.setNroTramite( rs.getString( COLUMN_NRO_TRAMITE ) );
		dto.setFecha( rs.getDate(COLUMN_FECHA ) );
		dto.setEstado( rs.getString( COLUMN_ESTADO ) );
		dto.setArea( rs.getString( COLUMN_AREA ) );
		dto.setSolicitante( rs.getString( COLUMN_SOLICITANTE ) );
	}

	/** 
	 * Resets the modified attributes in the DTO
	 */
	protected void reset(Solicitud dto)
	{
	}

	/** 
	 * Returns all rows from the Solicitud table that match the specified arbitrary SQL statement
	 */
	public Solicitud[] findByDynamicSelect(String sql, Object[] sqlParams) throws SolicitudDaoException
	{
		// declare variables
		final boolean isConnSupplied = (userConn != null);
		Connection conn = null;
		PreparedStatement stmt = null;
		ResultSet rs = null;
		
		try {
			// get the user-specified connection or get a connection from the ResourceManager
			conn = isConnSupplied ? userConn : ResourceManager.getConnection();
		
			// construct the SQL statement
			final String SQL = sql;
		
		
			System.out.println( "Executing " + SQL );
			// prepare statement
			stmt = conn.prepareStatement( SQL );
			stmt.setMaxRows( maxRows );
		
			// bind parameters
			for (int i=0; sqlParams!=null && i<sqlParams.length; i++ ) {
				stmt.setObject( i+1, sqlParams[i] );
			}
		
		
			rs = stmt.executeQuery();
		
			// fetch the results
			return fetchMultiResults(rs);
		}
		catch (Exception _e) {
			_e.printStackTrace();
			throw new SolicitudDaoException( "Exception: " + _e.getMessage(), _e );
		}
		finally {
			ResourceManager.close(rs);
			ResourceManager.close(stmt);
			if (!isConnSupplied) {
				ResourceManager.close(conn);
			}
		
		}
		
	}

	/** 
	 * Returns all rows from the Solicitud table that match the specified arbitrary SQL statement
	 */
	public Solicitud[] findByDynamicWhere(String sql, Object[] sqlParams) throws SolicitudDaoException
	{
		// declare variables
		final boolean isConnSupplied = (userConn != null);
		Connection conn = null;
		PreparedStatement stmt = null;
		ResultSet rs = null;
		
		try {
			// get the user-specified connection or get a connection from the ResourceManager
			conn = isConnSupplied ? userConn : ResourceManager.getConnection();
		
			// construct the SQL statement
			final String SQL = SQL_SELECT + " WHERE " + sql;
		
		
			System.out.println( "Executing " + SQL );
			// prepare statement
			stmt = conn.prepareStatement( SQL );
			stmt.setMaxRows( maxRows );
		
			// bind parameters
			for (int i=0; sqlParams!=null && i<sqlParams.length; i++ ) {
				stmt.setObject( i+1, sqlParams[i] );
			}
		
		
			rs = stmt.executeQuery();
		
			// fetch the results
			return fetchMultiResults(rs);
		}
		catch (Exception _e) {
			_e.printStackTrace();
			throw new SolicitudDaoException( "Exception: " + _e.getMessage(), _e );
		}
		finally {
			ResourceManager.close(rs);
			ResourceManager.close(stmt);
			if (!isConnSupplied) {
				ResourceManager.close(conn);
			}
		
		}
		
	}

}
