/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package com.SIGIA.app.example;

import java.math.*;
import java.util.Date;
import java.util.Collection;
import com.SIGIA.app.dao.ActividadDao;
import com.SIGIA.app.dto.Actividad;
import com.SIGIA.app.exceptions.ActividadDaoException;
import com.SIGIA.app.factory.ActividadDaoFactory;

public class ActividadDaoSample
{
	/**
	 * Method 'main'
	 * 
	 * @param arg
	 * @throws Exception
	 */
	public static void main(String[] arg) throws Exception
	{
		// Uncomment one of the lines below to test the generated code
		
		// findAll();
		// findByUsuario(0);
		// findWhereIdActividadEquals(0);
		// findWhereAreaAfectadaEquals("");
		// findWhereAccionRealizadaEquals("");
		// findWhereFechaEquals(null);
		// findWhereDescripcionEquals("");
		// findWhereIdUsuarioEquals(0);
	}

	/**
	 * Method 'findAll'
	 * 
	 */
	public static void findAll()
	{
		try {
			ActividadDao _dao = getActividadDao();
			Actividad _result[] = _dao.findAll();
			for (int i=0; i<_result.length; i++ ) {
				display( _result[i] );
			}
		
		}
		catch (Exception _e) {
			_e.printStackTrace();
		}
		
	}

	/**
	 * Method 'findByUsuario'
	 * 
	 * @param idUsuario
	 */
	public static void findByUsuario(int idUsuario)
	{
		try {
			ActividadDao _dao = getActividadDao();
			Actividad _result[] = _dao.findByUsuario(idUsuario);
			for (int i=0; i<_result.length; i++ ) {
				display( _result[i] );
			}
		
		}
		catch (Exception _e) {
			_e.printStackTrace();
		}
		
	}

	/**
	 * Method 'findWhereIdActividadEquals'
	 * 
	 * @param idActividad
	 */
	public static void findWhereIdActividadEquals(int idActividad)
	{
		try {
			ActividadDao _dao = getActividadDao();
			Actividad _result[] = _dao.findWhereIdActividadEquals(idActividad);
			for (int i=0; i<_result.length; i++ ) {
				display( _result[i] );
			}
		
		}
		catch (Exception _e) {
			_e.printStackTrace();
		}
		
	}

	/**
	 * Method 'findWhereAreaAfectadaEquals'
	 * 
	 * @param areaAfectada
	 */
	public static void findWhereAreaAfectadaEquals(String areaAfectada)
	{
		try {
			ActividadDao _dao = getActividadDao();
			Actividad _result[] = _dao.findWhereAreaAfectadaEquals(areaAfectada);
			for (int i=0; i<_result.length; i++ ) {
				display( _result[i] );
			}
		
		}
		catch (Exception _e) {
			_e.printStackTrace();
		}
		
	}

	/**
	 * Method 'findWhereAccionRealizadaEquals'
	 * 
	 * @param accionRealizada
	 */
	public static void findWhereAccionRealizadaEquals(String accionRealizada)
	{
		try {
			ActividadDao _dao = getActividadDao();
			Actividad _result[] = _dao.findWhereAccionRealizadaEquals(accionRealizada);
			for (int i=0; i<_result.length; i++ ) {
				display( _result[i] );
			}
		
		}
		catch (Exception _e) {
			_e.printStackTrace();
		}
		
	}

	/**
	 * Method 'findWhereFechaEquals'
	 * 
	 * @param fecha
	 */
	public static void findWhereFechaEquals(Date fecha)
	{
		try {
			ActividadDao _dao = getActividadDao();
			Actividad _result[] = _dao.findWhereFechaEquals(fecha);
			for (int i=0; i<_result.length; i++ ) {
				display( _result[i] );
			}
		
		}
		catch (Exception _e) {
			_e.printStackTrace();
		}
		
	}

	/**
	 * Method 'findWhereDescripcionEquals'
	 * 
	 * @param descripcion
	 */
	public static void findWhereDescripcionEquals(String descripcion)
	{
		try {
			ActividadDao _dao = getActividadDao();
			Actividad _result[] = _dao.findWhereDescripcionEquals(descripcion);
			for (int i=0; i<_result.length; i++ ) {
				display( _result[i] );
			}
		
		}
		catch (Exception _e) {
			_e.printStackTrace();
		}
		
	}

	/**
	 * Method 'findWhereIdUsuarioEquals'
	 * 
	 * @param idUsuario
	 */
	public static void findWhereIdUsuarioEquals(int idUsuario)
	{
		try {
			ActividadDao _dao = getActividadDao();
			Actividad _result[] = _dao.findWhereIdUsuarioEquals(idUsuario);
			for (int i=0; i<_result.length; i++ ) {
				display( _result[i] );
			}
		
		}
		catch (Exception _e) {
			_e.printStackTrace();
		}
		
	}

	/**
	 * Method 'getActividadDao'
	 * 
	 * @return ActividadDao
	 */
	public static ActividadDao getActividadDao()
	{
		return ActividadDaoFactory.create();
	}

	/**
	 * Method 'display'
	 * 
	 * @param dto
	 */
	public static void display(Actividad dto)
	{
		StringBuffer buf = new StringBuffer();
		buf.append( dto.getIdActividad() );
		buf.append( ", " );
		buf.append( dto.getAreaAfectada() );
		buf.append( ", " );
		buf.append( dto.getAccionRealizada() );
		buf.append( ", " );
		buf.append( dto.getFecha() );
		buf.append( ", " );
		buf.append( dto.getDescripcion() );
		buf.append( ", " );
		buf.append( dto.getIdUsuario() );
		System.out.println( buf.toString() );
	}

}
