/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package com.SIGIA.app.example;

import java.math.*;
import java.util.Date;
import java.util.Collection;
import com.SIGIA.app.dao.UsuarioDao;
import com.SIGIA.app.dto.Usuario;
import com.SIGIA.app.exceptions.UsuarioDaoException;
import com.SIGIA.app.factory.UsuarioDaoFactory;

public class UsuarioDaoSample
{
	/**
	 * Method 'main'
	 * 
	 * @param arg
	 * @throws Exception
	 */
	public static void main(String[] arg) throws Exception
	{
		// Uncomment one of the lines below to test the generated code
		
		// findAll();
		// findWhereIdUsuarioEquals(0);
		// findWhereDniEquals("");
		// findWhereNombreEquals("");
		// findWhereCorreoEquals("");
		// findWhereContrasenaEquals("");
		// findWhereRolEquals("");
		// findWhereEstadoEquals(0);
	}

	/**
	 * Method 'findAll'
	 * 
	 */
	public static void findAll()
	{
		try {
			UsuarioDao _dao = getUsuarioDao();
			Usuario _result[] = _dao.findAll();
			for (int i=0; i<_result.length; i++ ) {
				display( _result[i] );
			}
		
		}
		catch (Exception _e) {
			_e.printStackTrace();
		}
		
	}

	/**
	 * Method 'findWhereIdUsuarioEquals'
	 * 
	 * @param idUsuario
	 */
	public static void findWhereIdUsuarioEquals(int idUsuario)
	{
		try {
			UsuarioDao _dao = getUsuarioDao();
			Usuario _result[] = _dao.findWhereIdUsuarioEquals(idUsuario);
			for (int i=0; i<_result.length; i++ ) {
				display( _result[i] );
			}
		
		}
		catch (Exception _e) {
			_e.printStackTrace();
		}
		
	}

	/**
	 * Method 'findWhereDniEquals'
	 * 
	 * @param dni
	 */
	public static void findWhereDniEquals(String dni)
	{
		try {
			UsuarioDao _dao = getUsuarioDao();
			Usuario _result[] = _dao.findWhereDniEquals(dni);
			for (int i=0; i<_result.length; i++ ) {
				display( _result[i] );
			}
		
		}
		catch (Exception _e) {
			_e.printStackTrace();
		}
		
	}

	/**
	 * Method 'findWhereNombreEquals'
	 * 
	 * @param nombre
	 */
	public static void findWhereNombreEquals(String nombre)
	{
		try {
			UsuarioDao _dao = getUsuarioDao();
			Usuario _result[] = _dao.findWhereNombreEquals(nombre);
			for (int i=0; i<_result.length; i++ ) {
				display( _result[i] );
			}
		
		}
		catch (Exception _e) {
			_e.printStackTrace();
		}
		
	}

	/**
	 * Method 'findWhereCorreoEquals'
	 * 
	 * @param correo
	 */
	public static void findWhereCorreoEquals(String correo)
	{
		try {
			UsuarioDao _dao = getUsuarioDao();
			Usuario _result[] = _dao.findWhereCorreoEquals(correo);
			for (int i=0; i<_result.length; i++ ) {
				display( _result[i] );
			}
		
		}
		catch (Exception _e) {
			_e.printStackTrace();
		}
		
	}

	/**
	 * Method 'findWhereContrasenaEquals'
	 * 
	 * @param contrasena
	 */
	public static void findWhereContrasenaEquals(String contrasena)
	{
		try {
			UsuarioDao _dao = getUsuarioDao();
			Usuario _result[] = _dao.findWhereContrasenaEquals(contrasena);
			for (int i=0; i<_result.length; i++ ) {
				display( _result[i] );
			}
		
		}
		catch (Exception _e) {
			_e.printStackTrace();
		}
		
	}

	/**
	 * Method 'findWhereRolEquals'
	 * 
	 * @param rol
	 */
	public static void findWhereRolEquals(String rol)
	{
		try {
			UsuarioDao _dao = getUsuarioDao();
			Usuario _result[] = _dao.findWhereRolEquals(rol);
			for (int i=0; i<_result.length; i++ ) {
				display( _result[i] );
			}
		
		}
		catch (Exception _e) {
			_e.printStackTrace();
		}
		
	}

	/**
	 * Method 'findWhereEstadoEquals'
	 * 
	 * @param estado
	 */
	public static void findWhereEstadoEquals(short estado)
	{
		try {
			UsuarioDao _dao = getUsuarioDao();
			Usuario _result[] = _dao.findWhereEstadoEquals(estado);
			for (int i=0; i<_result.length; i++ ) {
				display( _result[i] );
			}
		
		}
		catch (Exception _e) {
			_e.printStackTrace();
		}
		
	}

	/**
	 * Method 'getUsuarioDao'
	 * 
	 * @return UsuarioDao
	 */
	public static UsuarioDao getUsuarioDao()
	{
		return UsuarioDaoFactory.create();
	}

	/**
	 * Method 'display'
	 * 
	 * @param dto
	 */
	public static void display(Usuario dto)
	{
		StringBuffer buf = new StringBuffer();
		buf.append( dto.getIdUsuario() );
		buf.append( ", " );
		buf.append( dto.getDni() );
		buf.append( ", " );
		buf.append( dto.getNombre() );
		buf.append( ", " );
		buf.append( dto.getCorreo() );
		buf.append( ", " );
		buf.append( dto.getContrasena() );
		buf.append( ", " );
		buf.append( dto.getRol() );
		buf.append( ", " );
		buf.append( dto.getEstado() );
		System.out.println( buf.toString() );
	}

}
