/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package com.SIGIA.app.jdbc;

import com.SIGIA.app.dao.*;
import com.SIGIA.app.factory.*;
import com.SIGIA.app.dto.*;
import com.SIGIA.app.exceptions.*;
import java.sql.Connection;
import java.util.Collection;
import java.sql.PreparedStatement;
import java.sql.Statement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Time;
import java.util.List;
import java.util.Iterator;
import java.util.ArrayList;

public class ItemSolicitudDaoImpl extends AbstractDAO implements ItemSolicitudDao
{
	/** 
	 * The factory class for this DAO has two versions of the create() method - one that
takes no arguments and one that takes a Connection argument. If the Connection version
is chosen then the connection will be stored in this attribute and will be used by all
calls to this DAO, otherwise a new Connection will be allocated for each operation.
	 */
	protected java.sql.Connection userConn;

	/** 
	 * All finder methods in this class use this SELECT constant to build their queries
	 */
	protected final String SQL_SELECT = "SELECT idItem, idSolicitud, idInsumo, cantSolicitada, cantEntregada FROM " + getTableName() + "";

	/** 
	 * Finder methods will pass this value to the JDBC setMaxRows method
	 */
	protected int maxRows;

	/** 
	 * SQL INSERT statement for this table
	 */
	protected final String SQL_INSERT = "INSERT INTO " + getTableName() + " ( idItem, idSolicitud, idInsumo, cantSolicitada, cantEntregada ) VALUES ( ?, ?, ?, ?, ? )";

	/** 
	 * SQL UPDATE statement for this table
	 */
	protected final String SQL_UPDATE = "UPDATE " + getTableName() + " SET idItem = ?, idSolicitud = ?, idInsumo = ?, cantSolicitada = ?, cantEntregada = ? WHERE idItem = ?";

	/** 
	 * SQL DELETE statement for this table
	 */
	protected final String SQL_DELETE = "DELETE FROM " + getTableName() + " WHERE idItem = ?";

	/** 
	 * Index of column idItem
	 */
	protected static final int COLUMN_ID_ITEM = 1;

	/** 
	 * Index of column idSolicitud
	 */
	protected static final int COLUMN_ID_SOLICITUD = 2;

	/** 
	 * Index of column idInsumo
	 */
	protected static final int COLUMN_ID_INSUMO = 3;

	/** 
	 * Index of column cantSolicitada
	 */
	protected static final int COLUMN_CANT_SOLICITADA = 4;

	/** 
	 * Index of column cantEntregada
	 */
	protected static final int COLUMN_CANT_ENTREGADA = 5;

	/** 
	 * Number of columns
	 */
	protected static final int NUMBER_OF_COLUMNS = 5;

	/** 
	 * Index of primary-key column idItem
	 */
	protected static final int PK_COLUMN_ID_ITEM = 1;

	/** 
	 * Inserts a new row in the ItemSolicitud table.
	 */
	public ItemSolicitudPk insert(ItemSolicitud dto) throws ItemSolicitudDaoException
	{
		long t1 = System.currentTimeMillis();
		// declare variables
		final boolean isConnSupplied = (userConn != null);
		Connection conn = null;
		PreparedStatement stmt = null;
		ResultSet rs = null;
		
		try {
			// get the user-specified connection or get a connection from the ResourceManager
			conn = isConnSupplied ? userConn : ResourceManager.getConnection();
		
			stmt = conn.prepareStatement( SQL_INSERT, Statement.RETURN_GENERATED_KEYS );
			int index = 1;
			stmt.setInt( index++, dto.getIdItem() );
			stmt.setInt( index++, dto.getIdSolicitud() );
			stmt.setInt( index++, dto.getIdInsumo() );
			stmt.setInt( index++, dto.getCantSolicitada() );
			stmt.setInt( index++, dto.getCantEntregada() );
			System.out.println( "Executing " + SQL_INSERT + " with DTO: " + dto );
			int rows = stmt.executeUpdate();
			long t2 = System.currentTimeMillis();
			System.out.println( rows + " rows affected (" + (t2-t1) + " ms)" );
		
			// retrieve values from auto-increment columns
			rs = stmt.getGeneratedKeys();
			if (rs != null && rs.next()) {
				dto.setIdItem( rs.getInt( 1 ) );
			}
		
			reset(dto);
			return dto.createPk();
		}
		catch (Exception _e) {
			_e.printStackTrace();
			throw new ItemSolicitudDaoException( "Exception: " + _e.getMessage(), _e );
		}
		finally {
			ResourceManager.close(stmt);
			if (!isConnSupplied) {
				ResourceManager.close(conn);
			}
		
		}
		
	}

	/** 
	 * Updates a single row in the ItemSolicitud table.
	 */
	public void update(ItemSolicitudPk pk, ItemSolicitud dto) throws ItemSolicitudDaoException
	{
		long t1 = System.currentTimeMillis();
		// declare variables
		final boolean isConnSupplied = (userConn != null);
		Connection conn = null;
		PreparedStatement stmt = null;
		
		try {
			// get the user-specified connection or get a connection from the ResourceManager
			conn = isConnSupplied ? userConn : ResourceManager.getConnection();
		
			System.out.println( "Executing " + SQL_UPDATE + " with DTO: " + dto );
			stmt = conn.prepareStatement( SQL_UPDATE );
			int index=1;
			stmt.setInt( index++, dto.getIdItem() );
			stmt.setInt( index++, dto.getIdSolicitud() );
			stmt.setInt( index++, dto.getIdInsumo() );
			stmt.setInt( index++, dto.getCantSolicitada() );
			stmt.setInt( index++, dto.getCantEntregada() );
			stmt.setInt( 6, pk.getIdItem() );
			int rows = stmt.executeUpdate();
			reset(dto);
			long t2 = System.currentTimeMillis();
			System.out.println( rows + " rows affected (" + (t2-t1) + " ms)" );
		}
		catch (Exception _e) {
			_e.printStackTrace();
			throw new ItemSolicitudDaoException( "Exception: " + _e.getMessage(), _e );
		}
		finally {
			ResourceManager.close(stmt);
			if (!isConnSupplied) {
				ResourceManager.close(conn);
			}
		
		}
		
	}

	/** 
	 * Deletes a single row in the ItemSolicitud table.
	 */
	public void delete(ItemSolicitudPk pk) throws ItemSolicitudDaoException
	{
		long t1 = System.currentTimeMillis();
		// declare variables
		final boolean isConnSupplied = (userConn != null);
		Connection conn = null;
		PreparedStatement stmt = null;
		
		try {
			// get the user-specified connection or get a connection from the ResourceManager
			conn = isConnSupplied ? userConn : ResourceManager.getConnection();
		
			System.out.println( "Executing " + SQL_DELETE + " with PK: " + pk );
			stmt = conn.prepareStatement( SQL_DELETE );
			stmt.setInt( 1, pk.getIdItem() );
			int rows = stmt.executeUpdate();
			long t2 = System.currentTimeMillis();
			System.out.println( rows + " rows affected (" + (t2-t1) + " ms)" );
		}
		catch (Exception _e) {
			_e.printStackTrace();
			throw new ItemSolicitudDaoException( "Exception: " + _e.getMessage(), _e );
		}
		finally {
			ResourceManager.close(stmt);
			if (!isConnSupplied) {
				ResourceManager.close(conn);
			}
		
		}
		
	}

	/** 
	 * Returns the rows from the ItemSolicitud table that matches the specified primary-key value.
	 */
	public ItemSolicitud findByPrimaryKey(ItemSolicitudPk pk) throws ItemSolicitudDaoException
	{
		return findByPrimaryKey( pk.getIdItem() );
	}

	/** 
	 * Returns all rows from the ItemSolicitud table that match the criteria 'idItem = :idItem'.
	 */
	public ItemSolicitud findByPrimaryKey(int idItem) throws ItemSolicitudDaoException
	{
		ItemSolicitud ret[] = findByDynamicSelect( SQL_SELECT + " WHERE idItem = ?", new Object[] {  new Integer(idItem) } );
		return ret.length==0 ? null : ret[0];
	}

	/** 
	 * Returns all rows from the ItemSolicitud table that match the criteria ''.
	 */
	public ItemSolicitud[] findAll() throws ItemSolicitudDaoException
	{
		return findByDynamicSelect( SQL_SELECT + " ORDER BY idItem", null );
	}

	/** 
	 * Returns all rows from the ItemSolicitud table that match the criteria 'idSolicitud = :idSolicitud'.
	 */
	public ItemSolicitud[] findBySolicitud(int idSolicitud) throws ItemSolicitudDaoException
	{
		return findByDynamicSelect( SQL_SELECT + " WHERE idSolicitud = ?", new Object[] {  new Integer(idSolicitud) } );
	}

	/** 
	 * Returns all rows from the ItemSolicitud table that match the criteria 'idInsumo = :idInsumo'.
	 */
	public ItemSolicitud[] findByInsumo(int idInsumo) throws ItemSolicitudDaoException
	{
		return findByDynamicSelect( SQL_SELECT + " WHERE idInsumo = ?", new Object[] {  new Integer(idInsumo) } );
	}

	/** 
	 * Returns all rows from the ItemSolicitud table that match the criteria 'idItem = :idItem'.
	 */
	public ItemSolicitud[] findWhereIdItemEquals(int idItem) throws ItemSolicitudDaoException
	{
		return findByDynamicSelect( SQL_SELECT + " WHERE idItem = ? ORDER BY idItem", new Object[] {  new Integer(idItem) } );
	}

	/** 
	 * Returns all rows from the ItemSolicitud table that match the criteria 'idSolicitud = :idSolicitud'.
	 */
	public ItemSolicitud[] findWhereIdSolicitudEquals(int idSolicitud) throws ItemSolicitudDaoException
	{
		return findByDynamicSelect( SQL_SELECT + " WHERE idSolicitud = ? ORDER BY idSolicitud", new Object[] {  new Integer(idSolicitud) } );
	}

	/** 
	 * Returns all rows from the ItemSolicitud table that match the criteria 'idInsumo = :idInsumo'.
	 */
	public ItemSolicitud[] findWhereIdInsumoEquals(int idInsumo) throws ItemSolicitudDaoException
	{
		return findByDynamicSelect( SQL_SELECT + " WHERE idInsumo = ? ORDER BY idInsumo", new Object[] {  new Integer(idInsumo) } );
	}

	/** 
	 * Returns all rows from the ItemSolicitud table that match the criteria 'cantSolicitada = :cantSolicitada'.
	 */
	public ItemSolicitud[] findWhereCantSolicitadaEquals(int cantSolicitada) throws ItemSolicitudDaoException
	{
		return findByDynamicSelect( SQL_SELECT + " WHERE cantSolicitada = ? ORDER BY cantSolicitada", new Object[] {  new Integer(cantSolicitada) } );
	}

	/** 
	 * Returns all rows from the ItemSolicitud table that match the criteria 'cantEntregada = :cantEntregada'.
	 */
	public ItemSolicitud[] findWhereCantEntregadaEquals(int cantEntregada) throws ItemSolicitudDaoException
	{
		return findByDynamicSelect( SQL_SELECT + " WHERE cantEntregada = ? ORDER BY cantEntregada", new Object[] {  new Integer(cantEntregada) } );
	}

	/**
	 * Method 'ItemSolicitudDaoImpl'
	 * 
	 */
	public ItemSolicitudDaoImpl()
	{
	}

	/**
	 * Method 'ItemSolicitudDaoImpl'
	 * 
	 * @param userConn
	 */
	public ItemSolicitudDaoImpl(final java.sql.Connection userConn)
	{
		this.userConn = userConn;
	}

	/** 
	 * Sets the value of maxRows
	 */
	public void setMaxRows(int maxRows)
	{
		this.maxRows = maxRows;
	}

	/** 
	 * Gets the value of maxRows
	 */
	public int getMaxRows()
	{
		return maxRows;
	}

	/**
	 * Method 'getTableName'
	 * 
	 * @return String
	 */
	public String getTableName()
	{
		return "ItemSolicitud";
	}

	/** 
	 * Fetches a single row from the result set
	 */
	protected ItemSolicitud fetchSingleResult(ResultSet rs) throws SQLException
	{
		if (rs.next()) {
			ItemSolicitud dto = new ItemSolicitud();
			populateDto( dto, rs);
			return dto;
		} else {
			return null;
		}
		
	}

	/** 
	 * Fetches multiple rows from the result set
	 */
	protected ItemSolicitud[] fetchMultiResults(ResultSet rs) throws SQLException
	{
		Collection resultList = new ArrayList();
		while (rs.next()) {
			ItemSolicitud dto = new ItemSolicitud();
			populateDto( dto, rs);
			resultList.add( dto );
		}
		
		ItemSolicitud ret[] = new ItemSolicitud[ resultList.size() ];
		resultList.toArray( ret );
		return ret;
	}

	/** 
	 * Populates a DTO with data from a ResultSet
	 */
	protected void populateDto(ItemSolicitud dto, ResultSet rs) throws SQLException
	{
		dto.setIdItem( rs.getInt( COLUMN_ID_ITEM ) );
		dto.setIdSolicitud( rs.getInt( COLUMN_ID_SOLICITUD ) );
		dto.setIdInsumo( rs.getInt( COLUMN_ID_INSUMO ) );
		dto.setCantSolicitada( rs.getInt( COLUMN_CANT_SOLICITADA ) );
		dto.setCantEntregada( rs.getInt( COLUMN_CANT_ENTREGADA ) );
	}

	/** 
	 * Resets the modified attributes in the DTO
	 */
	protected void reset(ItemSolicitud dto)
	{
	}

	/** 
	 * Returns all rows from the ItemSolicitud table that match the specified arbitrary SQL statement
	 */
	public ItemSolicitud[] findByDynamicSelect(String sql, Object[] sqlParams) throws ItemSolicitudDaoException
	{
		// declare variables
		final boolean isConnSupplied = (userConn != null);
		Connection conn = null;
		PreparedStatement stmt = null;
		ResultSet rs = null;
		
		try {
			// get the user-specified connection or get a connection from the ResourceManager
			conn = isConnSupplied ? userConn : ResourceManager.getConnection();
		
			// construct the SQL statement
			final String SQL = sql;
		
		
			System.out.println( "Executing " + SQL );
			// prepare statement
			stmt = conn.prepareStatement( SQL );
			stmt.setMaxRows( maxRows );
		
			// bind parameters
			for (int i=0; sqlParams!=null && i<sqlParams.length; i++ ) {
				stmt.setObject( i+1, sqlParams[i] );
			}
		
		
			rs = stmt.executeQuery();
		
			// fetch the results
			return fetchMultiResults(rs);
		}
		catch (Exception _e) {
			_e.printStackTrace();
			throw new ItemSolicitudDaoException( "Exception: " + _e.getMessage(), _e );
		}
		finally {
			ResourceManager.close(rs);
			ResourceManager.close(stmt);
			if (!isConnSupplied) {
				ResourceManager.close(conn);
			}
		
		}
		
	}

	/** 
	 * Returns all rows from the ItemSolicitud table that match the specified arbitrary SQL statement
	 */
	public ItemSolicitud[] findByDynamicWhere(String sql, Object[] sqlParams) throws ItemSolicitudDaoException
	{
		// declare variables
		final boolean isConnSupplied = (userConn != null);
		Connection conn = null;
		PreparedStatement stmt = null;
		ResultSet rs = null;
		
		try {
			// get the user-specified connection or get a connection from the ResourceManager
			conn = isConnSupplied ? userConn : ResourceManager.getConnection();
		
			// construct the SQL statement
			final String SQL = SQL_SELECT + " WHERE " + sql;
		
		
			System.out.println( "Executing " + SQL );
			// prepare statement
			stmt = conn.prepareStatement( SQL );
			stmt.setMaxRows( maxRows );
		
			// bind parameters
			for (int i=0; sqlParams!=null && i<sqlParams.length; i++ ) {
				stmt.setObject( i+1, sqlParams[i] );
			}
		
		
			rs = stmt.executeQuery();
		
			// fetch the results
			return fetchMultiResults(rs);
		}
		catch (Exception _e) {
			_e.printStackTrace();
			throw new ItemSolicitudDaoException( "Exception: " + _e.getMessage(), _e );
		}
		finally {
			ResourceManager.close(rs);
			ResourceManager.close(stmt);
			if (!isConnSupplied) {
				ResourceManager.close(conn);
			}
		
		}
		
	}

}
