/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package com.SIGIA.app.factory;

import java.sql.Connection;
import com.SIGIA.app.dao.*;
import com.SIGIA.app.jdbc.*;

public class ActividadDaoFactory
{
	/**
	 * Method 'create'
	 * 
	 * @return ActividadDao
	 */
	public static ActividadDao create()
	{
		return new ActividadDaoImpl();
	}

	/**
	 * Method 'create'
	 * 
	 * @param conn
	 * @return ActividadDao
	 */
	public static ActividadDao create(Connection conn)
	{
		return new ActividadDaoImpl( conn );
	}

}
