/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package com.SIGIA.app.factory;

import java.sql.Connection;
import com.SIGIA.app.dao.*;
import com.SIGIA.app.jdbc.*;

public class ItemSolicitudDaoFactory
{
	/**
	 * Method 'create'
	 * 
	 * @return ItemSolicitudDao
	 */
	public static ItemSolicitudDao create()
	{
		return new ItemSolicitudDaoImpl();
	}

	/**
	 * Method 'create'
	 * 
	 * @param conn
	 * @return ItemSolicitudDao
	 */
	public static ItemSolicitudDao create(Connection conn)
	{
		return new ItemSolicitudDaoImpl( conn );
	}

}
