/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package com.SIGIApp.dto;

import com.SIGIApp.dao.*;
import com.SIGIApp.factory.*;
import com.SIGIApp.exceptions.*;
import java.io.Serializable;
import java.util.*;

public class Categoria implements Serializable
{
	/** 
	 * This attribute maps to the column idCategoria in the Categoria table.
	 */
	protected int idCategoria;

	/** 
	 * This attribute maps to the column nombre in the Categoria table.
	 */
	protected String nombre;

	/** 
	 * This attribute maps to the column Estado in the Categoria table.
	 */
	protected short estado;

	/**
	 * Method 'Categoria'
	 * 
	 */
	public Categoria()
	{
	}

	/**
	 * Method 'getIdCategoria'
	 * 
	 * @return int
	 */
	public int getIdCategoria()
	{
		return idCategoria;
	}

	/**
	 * Method 'setIdCategoria'
	 * 
	 * @param idCategoria
	 */
	public void setIdCategoria(int idCategoria)
	{
		this.idCategoria = idCategoria;
	}

	/**
	 * Method 'getNombre'
	 * 
	 * @return String
	 */
	public String getNombre()
	{
		return nombre;
	}

	/**
	 * Method 'setNombre'
	 * 
	 * @param nombre
	 */
	public void setNombre(String nombre)
	{
		this.nombre = nombre;
	}

	/**
	 * Method 'getEstado'
	 * 
	 * @return short
	 */
	public short getEstado()
	{
		return estado;
	}

	/**
	 * Method 'setEstado'
	 * 
	 * @param estado
	 */
	public void setEstado(short estado)
	{
		this.estado = estado;
	}

	/**
	 * Method 'equals'
	 * 
	 * @param _other
	 * @return boolean
	 */
	public boolean equals(Object _other)
	{
		if (_other == null) {
			return false;
		}
		
		if (_other == this) {
			return true;
		}
		
		if (!(_other instanceof Categoria)) {
			return false;
		}
		
		final Categoria _cast = (Categoria) _other;
		if (idCategoria != _cast.idCategoria) {
			return false;
		}
		
		if (nombre == null ? _cast.nombre != nombre : !nombre.equals( _cast.nombre )) {
			return false;
		}
		
		if (estado != _cast.estado) {
			return false;
		}
		
		return true;
	}

	/**
	 * Method 'hashCode'
	 * 
	 * @return int
	 */
	public int hashCode()
	{
		int _hashCode = 0;
		_hashCode = 29 * _hashCode + idCategoria;
		if (nombre != null) {
			_hashCode = 29 * _hashCode + nombre.hashCode();
		}
		
		_hashCode = 29 * _hashCode + (int) estado;
		return _hashCode;
	}

	/**
	 * Method 'createPk'
	 * 
	 * @return CategoriaPk
	 */
	public CategoriaPk createPk()
	{
		return new CategoriaPk(idCategoria);
	}

	/**
	 * Method 'toString'
	 * 
	 * @return String
	 */
	public String toString()
	{
		StringBuffer ret = new StringBuffer();
		ret.append( "com.SIGIApp.dto.Categoria: " );
		ret.append( "idCategoria=" + idCategoria );
		ret.append( ", nombre=" + nombre );
		ret.append( ", estado=" + estado );
		return ret.toString();
	}

}
