/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package com.SIGIApp.dto;

import java.io.Serializable;
import java.util.*;

public class Insumo implements Serializable
{
	/** 
	 * This attribute maps to the column idInsumo in the Insumo table.
	 */
	protected int idInsumo;

	/** 
	 * This attribute maps to the column nombre in the Insumo table.
	 */
	protected String nombre;

	/** 
	 * This attribute maps to the column categoria in the Insumo table.
	 */
	protected String categoria;

	/** 
	 * This attribute maps to the column stockActual in the Insumo table.
	 */
	protected int stockActual;

	/** 
	 * This attribute maps to the column stockMinimo in the Insumo table.
	 */
	protected int stockMinimo;

	/** 
	 * This attribute maps to the column critico in the Insumo table.
	 */
	protected short critico;

	/**
	 * Method 'Insumo'
	 * 
	 */
	public Insumo()
	{
	}

	/**
	 * Method 'getIdInsumo'
	 * 
	 * @return int
	 */
	public int getIdInsumo()
	{
		return idInsumo;
	}

	/**
	 * Method 'setIdInsumo'
	 * 
	 * @param idInsumo
	 */
	public void setIdInsumo(int idInsumo)
	{
		this.idInsumo = idInsumo;
	}

	/**
	 * Method 'getNombre'
	 * 
	 * @return String
	 */
	public String getNombre()
	{
		return nombre;
	}

	/**
	 * Method 'setNombre'
	 * 
	 * @param nombre
	 */
	public void setNombre(String nombre)
	{
		this.nombre = nombre;
	}

	/**
	 * Method 'getCategoria'
	 * 
	 * @return String
	 */
	public String getCategoria()
	{
		return categoria;
	}

	/**
	 * Method 'setCategoria'
	 * 
	 * @param categoria
	 */
	public void setCategoria(String categoria)
	{
		this.categoria = categoria;
	}

	/**
	 * Method 'getStockActual'
	 * 
	 * @return int
	 */
	public int getStockActual()
	{
		return stockActual;
	}

	/**
	 * Method 'setStockActual'
	 * 
	 * @param stockActual
	 */
	public void setStockActual(int stockActual)
	{
		this.stockActual = stockActual;
	}

	/**
	 * Method 'getStockMinimo'
	 * 
	 * @return int
	 */
	public int getStockMinimo()
	{
		return stockMinimo;
	}

	/**
	 * Method 'setStockMinimo'
	 * 
	 * @param stockMinimo
	 */
	public void setStockMinimo(int stockMinimo)
	{
		this.stockMinimo = stockMinimo;
	}

	/**
	 * Method 'getCritico'
	 * 
	 * @return short
	 */
	public short getCritico()
	{
		return critico;
	}

	/**
	 * Method 'setCritico'
	 * 
	 * @param critico
	 */
	public void setCritico(short critico)
	{
		this.critico = critico;
	}

	/**
	 * Method 'equals'
	 * 
	 * @param _other
	 * @return boolean
	 */
	public boolean equals(Object _other)
	{
		if (_other == null) {
			return false;
		}
		
		if (_other == this) {
			return true;
		}
		
		if (!(_other instanceof Insumo)) {
			return false;
		}
		
		final Insumo _cast = (Insumo) _other;
		if (idInsumo != _cast.idInsumo) {
			return false;
		}
		
		if (nombre == null ? _cast.nombre != nombre : !nombre.equals( _cast.nombre )) {
			return false;
		}
		
		if (categoria == null ? _cast.categoria != categoria : !categoria.equals( _cast.categoria )) {
			return false;
		}
		
		if (stockActual != _cast.stockActual) {
			return false;
		}
		
		if (stockMinimo != _cast.stockMinimo) {
			return false;
		}
		
		if (critico != _cast.critico) {
			return false;
		}
		
		return true;
	}

	/**
	 * Method 'hashCode'
	 * 
	 * @return int
	 */
	public int hashCode()
	{
		int _hashCode = 0;
		_hashCode = 29 * _hashCode + idInsumo;
		if (nombre != null) {
			_hashCode = 29 * _hashCode + nombre.hashCode();
		}
		
		if (categoria != null) {
			_hashCode = 29 * _hashCode + categoria.hashCode();
		}
		
		_hashCode = 29 * _hashCode + stockActual;
		_hashCode = 29 * _hashCode + stockMinimo;
		_hashCode = 29 * _hashCode + (int) critico;
		return _hashCode;
	}

	/**
	 * Method 'createPk'
	 * 
	 * @return InsumoPk
	 */
	public InsumoPk createPk()
	{
		return new InsumoPk(idInsumo);
	}

	/**
	 * Method 'toString'
	 * 
	 * @return String
	 */
	public String toString()
	{
		StringBuffer ret = new StringBuffer();
		ret.append( "com.SIGIA.app.dto.Insumo: " );
		ret.append( "idInsumo=" + idInsumo );
		ret.append( ", nombre=" + nombre );
		ret.append( ", categoria=" + categoria );
		ret.append( ", stockActual=" + stockActual );
		ret.append( ", stockMinimo=" + stockMinimo );
		ret.append( ", critico=" + critico );
		return ret.toString();
	}

}
