/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package com.SIGIApp.dto;

import java.io.Serializable;
import java.util.*;

public class ItemSolicitud implements Serializable
{
	/** 
	 * This attribute maps to the column idItem in the ItemSolicitud table.
	 */
	protected int idItem;

	/** 
	 * This attribute maps to the column idSolicitud in the ItemSolicitud table.
	 */
	protected int idSolicitud;

	/** 
	 * This attribute maps to the column idInsumo in the ItemSolicitud table.
	 */
	protected int idInsumo;

	/** 
	 * This attribute maps to the column cantSolicitada in the ItemSolicitud table.
	 */
	protected int cantSolicitada;

	/** 
	 * This attribute maps to the column cantEntregada in the ItemSolicitud table.
	 */
	protected int cantEntregada;

	/**
	 * Method 'ItemSolicitud'
	 * 
	 */
	public ItemSolicitud()
	{
	}

	/**
	 * Method 'getIdItem'
	 * 
	 * @return int
	 */
	public int getIdItem()
	{
		return idItem;
	}

	/**
	 * Method 'setIdItem'
	 * 
	 * @param idItem
	 */
	public void setIdItem(int idItem)
	{
		this.idItem = idItem;
	}

	/**
	 * Method 'getIdSolicitud'
	 * 
	 * @return int
	 */
	public int getIdSolicitud()
	{
		return idSolicitud;
	}

	/**
	 * Method 'setIdSolicitud'
	 * 
	 * @param idSolicitud
	 */
	public void setIdSolicitud(int idSolicitud)
	{
		this.idSolicitud = idSolicitud;
	}

	/**
	 * Method 'getIdInsumo'
	 * 
	 * @return int
	 */
	public int getIdInsumo()
	{
		return idInsumo;
	}

	/**
	 * Method 'setIdInsumo'
	 * 
	 * @param idInsumo
	 */
	public void setIdInsumo(int idInsumo)
	{
		this.idInsumo = idInsumo;
	}

	/**
	 * Method 'getCantSolicitada'
	 * 
	 * @return int
	 */
	public int getCantSolicitada()
	{
		return cantSolicitada;
	}

	/**
	 * Method 'setCantSolicitada'
	 * 
	 * @param cantSolicitada
	 */
	public void setCantSolicitada(int cantSolicitada)
	{
		this.cantSolicitada = cantSolicitada;
	}

	/**
	 * Method 'getCantEntregada'
	 * 
	 * @return int
	 */
	public int getCantEntregada()
	{
		return cantEntregada;
	}

	/**
	 * Method 'setCantEntregada'
	 * 
	 * @param cantEntregada
	 */
	public void setCantEntregada(int cantEntregada)
	{
		this.cantEntregada = cantEntregada;
	}

	/**
	 * Method 'equals'
	 * 
	 * @param _other
	 * @return boolean
	 */
	public boolean equals(Object _other)
	{
		if (_other == null) {
			return false;
		}
		
		if (_other == this) {
			return true;
		}
		
		if (!(_other instanceof ItemSolicitud)) {
			return false;
		}
		
		final ItemSolicitud _cast = (ItemSolicitud) _other;
		if (idItem != _cast.idItem) {
			return false;
		}
		
		if (idSolicitud != _cast.idSolicitud) {
			return false;
		}
		
		if (idInsumo != _cast.idInsumo) {
			return false;
		}
		
		if (cantSolicitada != _cast.cantSolicitada) {
			return false;
		}
		
		if (cantEntregada != _cast.cantEntregada) {
			return false;
		}
		
		return true;
	}

	/**
	 * Method 'hashCode'
	 * 
	 * @return int
	 */
	public int hashCode()
	{
		int _hashCode = 0;
		_hashCode = 29 * _hashCode + idItem;
		_hashCode = 29 * _hashCode + idSolicitud;
		_hashCode = 29 * _hashCode + idInsumo;
		_hashCode = 29 * _hashCode + cantSolicitada;
		_hashCode = 29 * _hashCode + cantEntregada;
		return _hashCode;
	}

	/**
	 * Method 'createPk'
	 * 
	 * @return ItemSolicitudPk
	 */
	public ItemSolicitudPk createPk()
	{
		return new ItemSolicitudPk(idItem);
	}

	/**
	 * Method 'toString'
	 * 
	 * @return String
	 */
	public String toString()
	{
		StringBuffer ret = new StringBuffer();
		ret.append( "com.SIGIA.app.dto.ItemSolicitud: " );
		ret.append( "idItem=" + idItem );
		ret.append( ", idSolicitud=" + idSolicitud );
		ret.append( ", idInsumo=" + idInsumo );
		ret.append( ", cantSolicitada=" + cantSolicitada );
		ret.append( ", cantEntregada=" + cantEntregada );
		return ret.toString();
	}

}
