/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package com.SIGIApp.dto;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

/** 
 * This class represents the primary key of the Transaccion table.
 */
public class TransaccionPk implements Serializable
{
	protected int idTransaccion;

	/** 
	 * This attribute represents whether the primitive attribute idTransaccion is null.
	 */
	protected boolean idTransaccionNull;

	/** 
	 * Sets the value of idTransaccion
	 */
	public void setIdTransaccion(int idTransaccion)
	{
		this.idTransaccion = idTransaccion;
	}

	/** 
	 * Gets the value of idTransaccion
	 */
	public int getIdTransaccion()
	{
		return idTransaccion;
	}

	/**
	 * Method 'TransaccionPk'
	 * 
	 */
	public TransaccionPk()
	{
	}

	/**
	 * Method 'TransaccionPk'
	 * 
	 * @param idTransaccion
	 */
	public TransaccionPk(final int idTransaccion)
	{
		this.idTransaccion = idTransaccion;
	}

	/** 
	 * Sets the value of idTransaccionNull
	 */
	public void setIdTransaccionNull(boolean idTransaccionNull)
	{
		this.idTransaccionNull = idTransaccionNull;
	}

	/** 
	 * Gets the value of idTransaccionNull
	 */
	public boolean isIdTransaccionNull()
	{
		return idTransaccionNull;
	}

	/**
	 * Method 'equals'
	 * 
	 * @param _other
	 * @return boolean
	 */
	public boolean equals(Object _other)
	{
		if (_other == null) {
			return false;
		}
		
		if (_other == this) {
			return true;
		}
		
		if (!(_other instanceof TransaccionPk)) {
			return false;
		}
		
		final TransaccionPk _cast = (TransaccionPk) _other;
		if (idTransaccion != _cast.idTransaccion) {
			return false;
		}
		
		if (idTransaccionNull != _cast.idTransaccionNull) {
			return false;
		}
		
		return true;
	}

	/**
	 * Method 'hashCode'
	 * 
	 * @return int
	 */
	public int hashCode()
	{
		int _hashCode = 0;
		_hashCode = 29 * _hashCode + idTransaccion;
		_hashCode = 29 * _hashCode + (idTransaccionNull ? 1 : 0);
		return _hashCode;
	}

	/**
	 * Method 'toString'
	 * 
	 * @return String
	 */
	public String toString()
	{
		StringBuffer ret = new StringBuffer();
		ret.append( "com.SIGIA.app.dto.TransaccionPk: " );
		ret.append( "idTransaccion=" + idTransaccion );
		return ret.toString();
	}

}
