/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package com.SIGIApp.dto;

import java.io.Serializable;
import java.util.*;

public class Usuario implements Serializable
{
	/** 
	 * This attribute maps to the column idUsuario in the Usuario table.
	 */
	protected int idUsuario;

	/** 
	 * This attribute maps to the column dni in the Usuario table.
	 */
	protected String dni;

	/** 
	 * This attribute maps to the column nombre in the Usuario table.
	 */
	protected String nombre;

	/** 
	 * This attribute maps to the column correo in the Usuario table.
	 */
	protected String correo;

	/** 
	 * This attribute maps to the column contrasena in the Usuario table.
	 */
	protected String contrasena;

	/** 
	 * This attribute maps to the column rol in the Usuario table.
	 */
	protected String rol;

	/** 
	 * This attribute maps to the column estado in the Usuario table.
	 */
	protected short estado;

	/** 
	 * This attribute represents whether the primitive attribute estado is null.
	 */
	protected boolean estadoNull = true;

	/**
	 * Method 'Usuario'
	 * 
	 */
	public Usuario()
	{
	}

	/**
	 * Method 'getIdUsuario'
	 * 
	 * @return int
	 */
	public int getIdUsuario()
	{
		return idUsuario;
	}

	/**
	 * Method 'setIdUsuario'
	 * 
	 * @param idUsuario
	 */
	public void setIdUsuario(int idUsuario)
	{
		this.idUsuario = idUsuario;
	}

	/**
	 * Method 'getDni'
	 * 
	 * @return String
	 */
	public String getDni()
	{
		return dni;
	}

	/**
	 * Method 'setDni'
	 * 
	 * @param dni
	 */
	public void setDni(String dni)
	{
		this.dni = dni;
	}

	/**
	 * Method 'getNombre'
	 * 
	 * @return String
	 */
	public String getNombre()
	{
		return nombre;
	}

	/**
	 * Method 'setNombre'
	 * 
	 * @param nombre
	 */
	public void setNombre(String nombre)
	{
		this.nombre = nombre;
	}

	/**
	 * Method 'getCorreo'
	 * 
	 * @return String
	 */
	public String getCorreo()
	{
		return correo;
	}

	/**
	 * Method 'setCorreo'
	 * 
	 * @param correo
	 */
	public void setCorreo(String correo)
	{
		this.correo = correo;
	}

	/**
	 * Method 'getContrasena'
	 * 
	 * @return String
	 */
	public String getContrasena()
	{
		return contrasena;
	}

	/**
	 * Method 'setContrasena'
	 * 
	 * @param contrasena
	 */
	public void setContrasena(String contrasena)
	{
		this.contrasena = contrasena;
	}

	/**
	 * Method 'getRol'
	 * 
	 * @return String
	 */
	public String getRol()
	{
		return rol;
	}

	/**
	 * Method 'setRol'
	 * 
	 * @param rol
	 */
	public void setRol(String rol)
	{
		this.rol = rol;
	}

	/**
	 * Method 'getEstado'
	 * 
	 * @return short
	 */
	public short getEstado()
	{
		return estado;
	}

	/**
	 * Method 'setEstado'
	 * 
	 * @param estado
	 */
	public void setEstado(short estado)
	{
		this.estado = estado;
		this.estadoNull = false;
	}

	/**
	 * Method 'setEstadoNull'
	 * 
	 * @param value
	 */
	public void setEstadoNull(boolean value)
	{
		this.estadoNull = value;
	}

	/**
	 * Method 'isEstadoNull'
	 * 
	 * @return boolean
	 */
	public boolean isEstadoNull()
	{
		return estadoNull;
	}

	/**
	 * Method 'equals'
	 * 
	 * @param _other
	 * @return boolean
	 */
	public boolean equals(Object _other)
	{
		if (_other == null) {
			return false;
		}
		
		if (_other == this) {
			return true;
		}
		
		if (!(_other instanceof Usuario)) {
			return false;
		}
		
		final Usuario _cast = (Usuario) _other;
		if (idUsuario != _cast.idUsuario) {
			return false;
		}
		
		if (dni == null ? _cast.dni != dni : !dni.equals( _cast.dni )) {
			return false;
		}
		
		if (nombre == null ? _cast.nombre != nombre : !nombre.equals( _cast.nombre )) {
			return false;
		}
		
		if (correo == null ? _cast.correo != correo : !correo.equals( _cast.correo )) {
			return false;
		}
		
		if (contrasena == null ? _cast.contrasena != contrasena : !contrasena.equals( _cast.contrasena )) {
			return false;
		}
		
		if (rol == null ? _cast.rol != rol : !rol.equals( _cast.rol )) {
			return false;
		}
		
		if (estado != _cast.estado) {
			return false;
		}
		
		if (estadoNull != _cast.estadoNull) {
			return false;
		}
		
		return true;
	}

	/**
	 * Method 'hashCode'
	 * 
	 * @return int
	 */
	public int hashCode()
	{
		int _hashCode = 0;
		_hashCode = 29 * _hashCode + idUsuario;
		if (dni != null) {
			_hashCode = 29 * _hashCode + dni.hashCode();
		}
		
		if (nombre != null) {
			_hashCode = 29 * _hashCode + nombre.hashCode();
		}
		
		if (correo != null) {
			_hashCode = 29 * _hashCode + correo.hashCode();
		}
		
		if (contrasena != null) {
			_hashCode = 29 * _hashCode + contrasena.hashCode();
		}
		
		if (rol != null) {
			_hashCode = 29 * _hashCode + rol.hashCode();
		}
		
		_hashCode = 29 * _hashCode + (int) estado;
		_hashCode = 29 * _hashCode + (estadoNull ? 1 : 0);
		return _hashCode;
	}

	/**
	 * Method 'createPk'
	 * 
	 * @return UsuarioPk
	 */
	public UsuarioPk createPk()
	{
		return new UsuarioPk(idUsuario);
	}

	/**
	 * Method 'toString'
	 * 
	 * @return String
	 */
	public String toString()
	{
		StringBuffer ret = new StringBuffer();
		ret.append( "com.SIGIA.app.dto.Usuario: " );
		ret.append( "idUsuario=" + idUsuario );
		ret.append( ", dni=" + dni );
		ret.append( ", nombre=" + nombre );
		ret.append( ", correo=" + correo );
		ret.append( ", contrasena=" + contrasena );
		ret.append( ", rol=" + rol );
		ret.append( ", estado=" + estado );
		return ret.toString();
	}

}
