/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package com.SIGIApp.factory;

import com.SIGIApp.jdbc.InsumoDaoImpl;
import com.SIGIApp.dao.InsumoDao;
import java.sql.Connection;

public class InsumoDaoFactory
{
	/**
	 * Method 'create'
	 * 
	 * @return InsumoDao
	 */
	public static InsumoDao create()
	{
		return new InsumoDaoImpl();
	}

	/**
	 * Method 'create'
	 * 
	 * @param conn
	 * @return InsumoDao
	 */
	public static InsumoDao create(Connection conn)
	{
		return new InsumoDaoImpl( conn );
	}

}
