/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package com.SIGIApp.factory;

import com.SIGIApp.jdbc.ItemSolicitudDaoImpl;
import com.SIGIApp.dao.ItemSolicitudDao;
import java.sql.Connection;

public class ItemSolicitudDaoFactory
{
	/**
	 * Method 'create'
	 * 
	 * @return ItemSolicitudDao
	 */
	public static ItemSolicitudDao create()
	{
		return new ItemSolicitudDaoImpl();
	}

	/**
	 * Method 'create'
	 * 
	 * @param conn
	 * @return ItemSolicitudDao
	 */
	public static ItemSolicitudDao create(Connection conn)
	{
		return new ItemSolicitudDaoImpl( conn );
	}

}
