/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package com.SIGIApp.factory;

import com.SIGIApp.jdbc.SolicitudDaoImpl;
import com.SIGIApp.dao.SolicitudDao;
import java.sql.Connection;

public class SolicitudDaoFactory
{
	/**
	 * Method 'create'
	 * 
	 * @return SolicitudDao
	 */
	public static SolicitudDao create()
	{
		return new SolicitudDaoImpl();
	}

	/**
	 * Method 'create'
	 * 
	 * @param conn
	 * @return SolicitudDao
	 */
	public static SolicitudDao create(Connection conn)
	{
		return new SolicitudDaoImpl( conn );
	}

}
