/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Userinterface;
import com.SIGIApp.dto.*;
import com.SIGIApp.exceptions.ActividadDaoException;
import com.SIGIApp.exceptions.InsumoDaoException;
import com.SIGIApp.exceptions.TransaccionDaoException;
import com.SIGIApp.jdbc.*;
import java.sql.SQLException;
import java.time.LocalDate;
import java.time.LocalDateTime;
/**
 *
 * @author Anita
 */
public class SolicitarInsumo extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(SolicitarInsumo.class.getName());
    private int idUsuario;
    private Insumo[] menuoptions;
    //InsumoDaoImpl insumos;

    /**
     * Creates new form SolicitarInsumo
     */
    public SolicitarInsumo() {
        initComponents();
        
    }
    
    public SolicitarInsumo(int idUsuario) {
        this.idUsuario = idUsuario;
        initComponents();
        OpcionesInsumo();
    }
    
    //Lee la Tabla insumos de la BD y los agrega cómo items en el menú
    private void OpcionesInsumo(){
        InsumoDaoImpl insumos = new InsumoDaoImpl();
       
        
        try {
            NombreInsumoList.addItem("");
            menuoptions = insumos.findAll();
            int i=0;
            while(i < menuoptions.length){
                System.out.println("insumo: "+ menuoptions[i].getNombre());
                NombreInsumoList.addItem(menuoptions[i].getNombre());
                i = i + 1;
            }   
            
        } catch (InsumoDaoException ex) {
            System.getLogger(SolicitarInsumo.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
        }
            
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialog1 = new javax.swing.JDialog();
        jPanel3 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jDialog2 = new javax.swing.JDialog();
        jPanel4 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        fareas = new javax.swing.JTextField();
        fcant = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        fnombs = new javax.swing.JTextField();
        bcancelar = new javax.swing.JButton();
        bconfirmar = new javax.swing.JButton();
        NombreInsumoList = new javax.swing.JComboBox<>();

        jPanel3.setBackground(new java.awt.Color(253, 242, 197));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(77, 64, 43));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Operación realizada");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 336, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(37, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(64, Short.MAX_VALUE)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(71, 71, 71))
        );

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jDialog2.setTitle("Stock Insuficiente");

        jPanel4.setBackground(new java.awt.Color(255, 204, 204));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("STOCK INSUFICIENTE");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 311, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(46, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(94, 94, 94)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(93, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jDialog2Layout = new javax.swing.GroupLayout(jDialog2.getContentPane());
        jDialog2.getContentPane().setLayout(jDialog2Layout);
        jDialog2Layout.setHorizontalGroup(
            jDialog2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jDialog2Layout.setVerticalGroup(
            jDialog2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(205, 216, 172));

        jPanel2.setBackground(new java.awt.Color(253, 242, 197));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 85, Short.MAX_VALUE)
        );

        jButton1.setBackground(new java.awt.Color(77, 64, 43));
        jButton1.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(253, 242, 197));
        jButton1.setText(" Volver");
        jButton1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("sansserif", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(77, 64, 43));
        jLabel1.setText("Solicitar Insumo");

        jLabel2.setFont(new java.awt.Font("sansserif", 1, 20)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(77, 64, 43));
        jLabel2.setText("Nombre Insumo *");

        fareas.setBackground(new java.awt.Color(253, 242, 197));
        fareas.setForeground(new java.awt.Color(77, 64, 43));

        fcant.setBackground(new java.awt.Color(253, 242, 197));
        fcant.setForeground(new java.awt.Color(77, 64, 43));
        fcant.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fcantActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("sansserif", 1, 20)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(77, 64, 43));
        jLabel3.setText("Área Solicitante*");

        jLabel4.setFont(new java.awt.Font("sansserif", 1, 20)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(77, 64, 43));
        jLabel4.setText("Cantidad*");

        jLabel5.setFont(new java.awt.Font("sansserif", 1, 20)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(77, 64, 43));
        jLabel5.setText("Nombre del Solicitante");

        fnombs.setBackground(new java.awt.Color(253, 242, 197));
        fnombs.setForeground(new java.awt.Color(77, 64, 43));

        bcancelar.setBackground(new java.awt.Color(77, 64, 43));
        bcancelar.setFont(new java.awt.Font("sansserif", 1, 20)); // NOI18N
        bcancelar.setForeground(new java.awt.Color(253, 242, 197));
        bcancelar.setText("Cancelar");
        bcancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bcancelarActionPerformed(evt);
            }
        });

        bconfirmar.setBackground(new java.awt.Color(77, 64, 43));
        bconfirmar.setFont(new java.awt.Font("sansserif", 1, 20)); // NOI18N
        bconfirmar.setForeground(new java.awt.Color(253, 242, 197));
        bconfirmar.setText("Confirmar");
        bconfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bconfirmarActionPerformed(evt);
            }
        });

        NombreInsumoList.setBackground(new java.awt.Color(253, 242, 197));
        NombreInsumoList.setForeground(new java.awt.Color(77, 64, 43));
        NombreInsumoList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                NombreInsumoListMouseClicked(evt);
            }
        });
        NombreInsumoList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NombreInsumoListActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 653, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(219, 219, 219)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(36, 36, 36))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel5)
                        .addComponent(jLabel2)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(bcancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(bconfirmar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(fnombs, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(fareas, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(fcant, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(NombreInsumoList, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 363, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60)
                .addComponent(jLabel1)
                .addGap(26, 26, 26)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(NombreInsumoList, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fareas, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fcant, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fnombs, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bconfirmar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bcancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(133, 133, 133))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void fcantActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fcantActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fcantActionPerformed

    private void bconfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bconfirmarActionPerformed
        // TODO add your handling code here:
        InsumoDaoImpl insumos = new InsumoDaoImpl();
        TransaccionDaoImpl transaccion = new TransaccionDaoImpl();
        ActividadDaoImpl actividades = new ActividadDaoImpl();
        NombreInsumoList.getSelectedItem();
        fareas.getText();
        fcant.getText();
        int cantidad;
        Transaccion pedido = new Transaccion();
        
        cantidad = Integer.parseInt(fcant.getText());
        fnombs.getText();
        
        
        try {
            //System.out.println(NombreInsumoList.getSelectedItem().toString());
            //Ver de hacer si el usuario ingresa un elemento que no está en la base de datos.
            Insumo tempo = insumos.buscarInsumoNombre(NombreInsumoList.getSelectedItem().toString());
            
            //Antes de insertar ver si el stockActual es mayor que el solicitado.
            if(tempo.getStockActual() > cantidad){
                //Cargo los datos ingresados para luego agregarlos a la tabla Transacciones
                pedido.setTipo("egreso");
                pedido.setCantidad(cantidad);
                pedido.setSolicitante(fnombs.getText());
                pedido.setAreaDestino(fareas.getText());
                pedido.setIdInsumo(tempo.getIdInsumo());
                pedido.setIdUsuario(idUsuario);
                
                //++++
                //+Inserto la nueva transacción en la tabla.
                //++++
                transaccion.insert(pedido);
                
                //++++
                //+Modifico la cantidad disponible del insumo en su tabla
                //++++
                
                int stockmodified = tempo.getStockActual() - cantidad;   
                
                tempo.setStockActual(stockmodified);
                InsumoPk insumoPk = new InsumoPk();
                insumoPk.setIdInsumo(tempo.getIdInsumo());
                //Hago la actualización
                insumos.update(insumoPk, tempo);
                
                
                //++++
                //+Guardo operación en tabla de Actividades
                //++++
                Actividad actividad = new Actividad();
                actividad.setAccionRealizada(pedido.getTipo());
                actividad.setAreaAfectada(pedido.getAreaDestino());
                actividad.setDescripcion(pedido.getTipo() + " de " + NombreInsumoList.getSelectedItem() + ". Id de usuario: " + idUsuario);
                //actividad.setIdActividad(cantidad);
                actividad.setIdUsuario(idUsuario);
                
                
                actividades.insert(actividad);
                jDialog1.setVisible(true);
            }else{
                //ejecutar cartel de stock no disponible ya que la cantidad pedida es mayor al stock actual
                jDialog2.setVisible(true);
            }
            
        } catch (SQLException ex) {
            System.getLogger(SolicitarInsumo.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
        } catch (TransaccionDaoException ex) {
            System.getLogger(SolicitarInsumo.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
        } catch (InsumoDaoException ex) {
            System.getLogger(SolicitarInsumo.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
        } catch (ActividadDaoException ex) {
            System.getLogger(SolicitarInsumo.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
        }
        
    }//GEN-LAST:event_bconfirmarActionPerformed

    private void NombreInsumoListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NombreInsumoListActionPerformed
        // TODO add your handling code here:

        
    }//GEN-LAST:event_NombreInsumoListActionPerformed

    private void NombreInsumoListMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NombreInsumoListMouseClicked
        // TODO add your handling code here:

    }//GEN-LAST:event_NombreInsumoListMouseClicked

    private void bcancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bcancelarActionPerformed
        // TODO add your handling code here:
        NombreInsumoList.setSelectedIndex(0);
        fareas.setText("");
        fcant.setText("");
        fnombs.setText("");
        //this.setVisible(false);
        
        
    }//GEN-LAST:event_bcancelarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new SolicitarInsumo().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> NombreInsumoList;
    private javax.swing.JButton bcancelar;
    private javax.swing.JButton bconfirmar;
    private javax.swing.JTextField fareas;
    private javax.swing.JTextField fcant;
    private javax.swing.JTextField fnombs;
    private javax.swing.JButton jButton1;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JDialog jDialog2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    // End of variables declaration//GEN-END:variables
}
