/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package com.SIGIA.app.dao;

import com.SIGIA.app.dto.*;
import com.SIGIA.app.exceptions.*;

public interface InsumoDao
{
	/** 
	 * Inserts a new row in the Insumo table.
	 */
	public InsumoPk insert(Insumo dto) throws InsumoDaoException;

	/** 
	 * Updates a single row in the Insumo table.
	 */
	public void update(InsumoPk pk, Insumo dto) throws InsumoDaoException;

	/** 
	 * Deletes a single row in the Insumo table.
	 */
	public void delete(InsumoPk pk) throws InsumoDaoException;

	/** 
	 * Returns the rows from the Insumo table that matches the specified primary-key value.
	 */
	public Insumo findByPrimaryKey(InsumoPk pk) throws InsumoDaoException;

	/** 
	 * Returns all rows from the Insumo table that match the criteria 'idInsumo = :idInsumo'.
	 */
	public Insumo findByPrimaryKey(int idInsumo) throws InsumoDaoException;

	/** 
	 * Returns all rows from the Insumo table that match the criteria ''.
	 */
	public Insumo[] findAll() throws InsumoDaoException;

	/** 
	 * Returns all rows from the Insumo table that match the criteria 'idInsumo = :idInsumo'.
	 */
	public Insumo[] findWhereIdInsumoEquals(int idInsumo) throws InsumoDaoException;

	/** 
	 * Returns all rows from the Insumo table that match the criteria 'nombre = :nombre'.
	 */
	public Insumo[] findWhereNombreEquals(String nombre) throws InsumoDaoException;

	/** 
	 * Returns all rows from the Insumo table that match the criteria 'categoria = :categoria'.
	 */
	public Insumo[] findWhereCategoriaEquals(String categoria) throws InsumoDaoException;

	/** 
	 * Returns all rows from the Insumo table that match the criteria 'stockActual = :stockActual'.
	 */
	public Insumo[] findWhereStockActualEquals(int stockActual) throws InsumoDaoException;

	/** 
	 * Returns all rows from the Insumo table that match the criteria 'stockMinimo = :stockMinimo'.
	 */
	public Insumo[] findWhereStockMinimoEquals(int stockMinimo) throws InsumoDaoException;

	/** 
	 * Returns all rows from the Insumo table that match the criteria 'critico = :critico'.
	 */
	public Insumo[] findWhereCriticoEquals(short critico) throws InsumoDaoException;

	/** 
	 * Sets the value of maxRows
	 */
	public void setMaxRows(int maxRows);

	/** 
	 * Gets the value of maxRows
	 */
	public int getMaxRows();

	/** 
	 * Returns all rows from the Insumo table that match the specified arbitrary SQL statement
	 */
	public Insumo[] findByDynamicSelect(String sql, Object[] sqlParams) throws InsumoDaoException;

	/** 
	 * Returns all rows from the Insumo table that match the specified arbitrary SQL statement
	 */
	public Insumo[] findByDynamicWhere(String sql, Object[] sqlParams) throws InsumoDaoException;

}
